//! agent-scaffold: scaffold the agent workflow into a project.
//!
//! Two-tier ownership from the spec:
//!
//! - Reference assets (tool-owned, under `.agents/`) are always refreshed.
//! - Working files (the root `AGENTS.md` and the plan template) are
//!   create-if-absent unless `--force`.
//!
//! `AGENTS.md` is generated by rendering the selected principles into the
//! pack's guidance template; the other assets are dropped verbatim.

mod manifest;
mod pack;
mod tui;

use {
	clap::Parser,
	manifest::{
		Asset,
		Ownership,
	},
	pack::Detail,
	std::{
		collections::HashMap,
		fs,
		io,
		path::{
			Path,
			PathBuf,
		},
	},
};

/// What happened to a single asset on a scaffold run.
#[derive(Debug, PartialEq, Eq)]
enum Outcome {
	Created,
	Refreshed,
	SkippedExisting,
	Overwritten,
}

impl Outcome {
	fn label(&self) -> &'static str {
		match self {
			Outcome::Created => "created",
			Outcome::Refreshed => "refreshed",
			Outcome::SkippedExisting => "skipped (exists)",
			Outcome::Overwritten => "overwritten",
		}
	}
}

/// Write one asset under `root`, honouring its ownership and `force`.
fn write_asset(
	root: &Path,
	asset: &Asset,
	force: bool,
) -> io::Result<Outcome> {
	let dest = root.join(&asset.dest);
	let exists = dest.exists();

	let outcome = match asset.ownership {
		Ownership::Reference =>
			if exists {
				Outcome::Refreshed
			} else {
				Outcome::Created
			},
		Ownership::Working =>
			if exists {
				if force {
					Outcome::Overwritten
				} else {
					return Ok(Outcome::SkippedExisting);
				}
			} else {
				Outcome::Created
			},
	};

	if let Some(parent) = dest.parent() {
		fs::create_dir_all(parent)?;
	}
	fs::write(&dest, &asset.contents)?;
	Ok(outcome)
}

/// Scaffold a pack's asset set, returning each asset's path and outcome. Assets
/// come from `source`'s manifest; `{{principles}}` is rendered from the current
/// selection and `overrides` supplies the `--var` values for any variables the
/// pack declares.
fn scaffold(
	source: &manifest::PackSource,
	root: &Path,
	selected: &[&pack::Principle],
	detail: Detail,
	overrides: &HashMap<String, String>,
	force: bool,
) -> Result<Vec<(String, Outcome)>, manifest::LoadError> {
	let mut builtin: HashMap<String, String> = HashMap::new();
	builtin.insert("principles".to_string(), pack::render_principles(selected, detail));
	manifest::load(source, &builtin, overrides)?
		.into_iter()
		.map(|asset| write_asset(root, &asset, force).map(|outcome| (asset.dest, outcome)))
		.collect::<io::Result<Vec<_>>>()
		.map_err(manifest::LoadError::from)
}

/// Scaffold the agent workflow into a project.
#[derive(Parser)]
#[command(name = "agent-scaffold", about, version)]
struct Cli {
	/// Directory to scaffold into (defaults to the current directory).
	#[arg(long, default_value = ".")]
	output_dir: PathBuf,
	/// Overwrite existing user working files instead of leaving them untouched.
	#[arg(long)]
	force: bool,
	/// Which principles to include: default, all, none, or a comma-separated list of ids.
	#[arg(long, default_value = "default")]
	principles: String,
	/// How much of each principle to render into the output.
	#[arg(long, value_enum, default_value_t = Detail::Summary)]
	principle_detail: Detail,
	/// Print the default-selected principles (numbered) and exit, without scaffolding.
	#[arg(long)]
	list_principles: bool,
	/// Choose principles interactively in a two-pane selector, seeded from `--principles`.
	#[arg(long, short)]
	interactive: bool,
	/// Scaffold from a user-supplied pack directory instead of the built-in one.
	#[arg(long)]
	template: Option<PathBuf>,
	/// Set a pack-declared variable, as `--var key=value` (repeatable).
	#[arg(long = "var", value_name = "KEY=VALUE")]
	var: Vec<String>,
}

fn main() -> io::Result<()> {
	let cli = Cli::parse();

	// The active pack: the built-in one, or an external directory via --template.
	let source = match &cli.template {
		Some(path) => manifest::PackSource::Directory(path.clone()),
		None => manifest::builtin(),
	};

	// Parse --var key=value overrides. Validation against the pack's declared
	// variables happens in the loader; here we only reject malformed entries.
	let mut overrides: HashMap<String, String> = HashMap::new();
	for entry in &cli.var {
		match entry.split_once('=') {
			Some((key, value)) => {
				overrides.insert(key.to_string(), value.to_string());
			}
			None => {
				eprintln!("error: --var expects key=value, got `{entry}`");
				std::process::exit(2);
			}
		}
	}

	let principles = pack::default_principles();
	let selected = match pack::resolve_selection(&principles, &cli.principles) {
		Ok(selected) => selected,
		Err(error) => {
			eprintln!("error: {error}");
			std::process::exit(2);
		}
	};

	if cli.list_principles {
		println!("{}", pack::render_principles(&selected, cli.principle_detail));
		return Ok(());
	}

	// Interactive selection overrides the resolved set, seeded from it. On
	// confirm it prints a `--principles` line so the exact selection and order
	// can be replayed non-interactively; on abort nothing is written.
	let selected = if cli.interactive {
		let initial: Vec<usize> = selected
			.iter()
			.map(|p| {
				principles
					.iter()
					.position(|q| q.id == p.id)
					.expect("selected principle is from the pack")
			})
			.collect();
		let save_summary = vec![
			format!("Scaffold into: {}", cli.output_dir.display()),
			"Creates AGENTS.md and docs/plans/TEMPLATE.md if absent;".to_string(),
			"always refreshes the .agents/ reference assets.".to_string(),
			if cli.force {
				"Existing working files WILL be overwritten (--force).".to_string()
			} else {
				"Existing working files are left untouched.".to_string()
			},
		];
		match tui::run_selection(&principles, &initial, save_summary)? {
			Some(order) => {
				let chosen: Vec<&pack::Principle> = order.iter().map(|&i| &principles[i]).collect();
				let ids: Vec<&str> = chosen.iter().map(|p| p.id.as_str()).collect();
				println!("selection: --principles {}", ids.join(","));
				chosen
			}
			None => {
				eprintln!("aborted; nothing written");
				return Ok(());
			}
		}
	} else {
		selected
	};

	let results = match scaffold(
		&source,
		&cli.output_dir,
		&selected,
		cli.principle_detail,
		&overrides,
		cli.force,
	) {
		Ok(results) => results,
		Err(error) => {
			eprintln!("error: {error}");
			std::process::exit(2);
		}
	};
	for (path, outcome) in results {
		println!("{:>16}  {}", outcome.label(), path);
	}
	Ok(())
}

#[cfg(test)]
mod tests {
	use super::*;

	/// A unique scratch directory under the system temp dir for one test.
	fn scratch(name: &str) -> PathBuf {
		let dir = std::env::temp_dir().join(format!(
			"agent-scaffold-poc-{}-{}",
			std::process::id(),
			name
		));
		let _ = fs::remove_dir_all(&dir);
		dir
	}

	#[test]
	fn first_run_creates_everything() {
		let root = scratch("first-run");
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();
		let results = scaffold(
			&manifest::builtin(),
			&root,
			&selected,
			Detail::Summary,
			&HashMap::new(),
			false,
		)
		.unwrap();
		assert!(results.iter().all(|(_, o)| *o == Outcome::Created));
		assert!(root.join("AGENTS.md").exists());
		assert!(root.join(".agents/principles.toml").exists());
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn generated_agents_has_principles_and_no_placeholder() {
		let root = scratch("generated");
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();
		scaffold(&manifest::builtin(), &root, &selected, Detail::Summary, &HashMap::new(), false)
			.unwrap();
		let agents = fs::read_to_string(root.join("AGENTS.md")).unwrap();
		assert!(!agents.contains("{{principles}}"));
		assert!(agents.contains("1. "));
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn rerun_refreshes_reference_but_skips_working() {
		let root = scratch("rerun");
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();
		scaffold(&manifest::builtin(), &root, &selected, Detail::Summary, &HashMap::new(), false)
			.unwrap();

		// A user edits a working file after the first run.
		fs::write(root.join("AGENTS.md"), "user edits\n").unwrap();

		let results = scaffold(
			&manifest::builtin(),
			&root,
			&selected,
			Detail::Summary,
			&HashMap::new(),
			false,
		)
		.unwrap();
		let outcome_of =
			|p: &str| results.iter().find(|(path, _)| *path == p).map(|(_, o)| o).unwrap();

		// Reference assets are refreshed; the edited working file is left alone.
		assert_eq!(*outcome_of(".agents/principles.toml"), Outcome::Refreshed);
		assert_eq!(*outcome_of("AGENTS.md"), Outcome::SkippedExisting);
		assert_eq!(fs::read_to_string(root.join("AGENTS.md")).unwrap(), "user edits\n");
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn force_overwrites_working_files() {
		let root = scratch("force");
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();
		scaffold(&manifest::builtin(), &root, &selected, Detail::Summary, &HashMap::new(), false)
			.unwrap();
		fs::write(root.join("AGENTS.md"), "user edits\n").unwrap();

		let results = scaffold(
			&manifest::builtin(),
			&root,
			&selected,
			Detail::Summary,
			&HashMap::new(),
			true,
		)
		.unwrap();
		let agents = results.iter().find(|(path, _)| *path == "AGENTS.md").map(|(_, o)| o).unwrap();
		assert_eq!(*agents, Outcome::Overwritten);
		let contents = fs::read_to_string(root.join("AGENTS.md")).unwrap();
		assert_ne!(contents, "user edits\n");
		assert!(contents.starts_with("# Agent guidance"));
		fs::remove_dir_all(&root).unwrap();
	}
}
