//! agent-scaffold: scaffold the agent workflow into a project.
//!
//! Two-tier ownership from the spec:
//!
//! - Reference assets (tool-owned, under `.agents/`) are always refreshed.
//! - Working files (the root `AGENTS.md` and the plan template) are
//!   create-if-absent unless `--force`.
//!
//! `AGENTS.md` is generated by rendering the selected principles into the
//! pack's guidance template; the other assets are dropped verbatim.

mod pack;
mod tui;

use {
	clap::Parser,
	pack::Detail,
	std::{
		fs,
		io,
		path::{
			Path,
			PathBuf,
		},
	},
};

const AGENTS_TEMPLATE: &str = include_str!("../pack/AGENTS.md");
const PLAN_TEMPLATE: &str = include_str!("../pack/plan-template.md");
const PROMPT_CLARIFYING: &str = include_str!("../pack/prompts/clarifying-questions.md");
const PROMPT_GATE: &str = include_str!("../pack/prompts/open-questions-gate.md");
const PROMPT_REVIEW: &str = include_str!("../pack/prompts/adversarial-review.md");

/// Whether a scaffolded asset is owned by the tool or by the user.
#[derive(Clone, Copy)]
enum Ownership {
	/// Tool-owned reference asset: always (re)written to stay current.
	Reference,
	/// User working file: created only if absent, unless forced.
	Working,
}

/// A single asset the tool drops into the output directory.
struct Asset {
	/// Path relative to the output directory.
	path: &'static str,
	contents: String,
	ownership: Ownership,
}

/// Build the asset set to drop. `AGENTS.md` is rendered from the pack; the root
/// copy is a working file and the `.agents/` copy is a tool-owned reference.
fn assets(
	selected: &[&pack::Principle],
	detail: Detail,
) -> Vec<Asset> {
	let agents = pack::render_agents(AGENTS_TEMPLATE, selected, detail);
	vec![
		Asset {
			path: "AGENTS.md",
			contents: agents.clone(),
			ownership: Ownership::Working,
		},
		Asset {
			path: "docs/plans/TEMPLATE.md",
			contents: PLAN_TEMPLATE.to_string(),
			ownership: Ownership::Working,
		},
		Asset {
			path: ".agents/AGENTS.reference.md",
			contents: agents,
			ownership: Ownership::Reference,
		},
		Asset {
			path: ".agents/prompts/clarifying-questions.md",
			contents: PROMPT_CLARIFYING.to_string(),
			ownership: Ownership::Reference,
		},
		Asset {
			path: ".agents/prompts/open-questions-gate.md",
			contents: PROMPT_GATE.to_string(),
			ownership: Ownership::Reference,
		},
		Asset {
			path: ".agents/prompts/adversarial-review.md",
			contents: PROMPT_REVIEW.to_string(),
			ownership: Ownership::Reference,
		},
		Asset {
			path: ".agents/principles.toml",
			contents: pack::DEFAULT_PRINCIPLES_TOML.to_string(),
			ownership: Ownership::Reference,
		},
	]
}

/// What happened to a single asset on a scaffold run.
#[derive(Debug, PartialEq, Eq)]
enum Outcome {
	Created,
	Refreshed,
	SkippedExisting,
	Overwritten,
}

impl Outcome {
	fn label(&self) -> &'static str {
		match self {
			Outcome::Created => "created",
			Outcome::Refreshed => "refreshed",
			Outcome::SkippedExisting => "skipped (exists)",
			Outcome::Overwritten => "overwritten",
		}
	}
}

/// Write one asset under `root`, honouring its ownership and `force`.
fn write_asset(
	root: &Path,
	asset: &Asset,
	force: bool,
) -> io::Result<Outcome> {
	let dest = root.join(asset.path);
	let exists = dest.exists();

	let outcome = match asset.ownership {
		Ownership::Reference =>
			if exists {
				Outcome::Refreshed
			} else {
				Outcome::Created
			},
		Ownership::Working =>
			if exists {
				if force {
					Outcome::Overwritten
				} else {
					return Ok(Outcome::SkippedExisting);
				}
			} else {
				Outcome::Created
			},
	};

	if let Some(parent) = dest.parent() {
		fs::create_dir_all(parent)?;
	}
	fs::write(&dest, &asset.contents)?;
	Ok(outcome)
}

/// Scaffold the whole asset set, returning each asset's path and outcome.
fn scaffold(
	root: &Path,
	selected: &[&pack::Principle],
	detail: Detail,
	force: bool,
) -> io::Result<Vec<(&'static str, Outcome)>> {
	assets(selected, detail)
		.into_iter()
		.map(|asset| write_asset(root, &asset, force).map(|outcome| (asset.path, outcome)))
		.collect()
}

/// Scaffold the agent workflow into a project.
#[derive(Parser)]
#[command(name = "agent-scaffold", about, version)]
struct Cli {
	/// Directory to scaffold into (defaults to the current directory).
	#[arg(long, default_value = ".")]
	output_dir: PathBuf,
	/// Overwrite existing user working files instead of leaving them untouched.
	#[arg(long)]
	force: bool,
	/// Which principles to include: default, all, none, or a comma-separated list of ids.
	#[arg(long, default_value = "default")]
	principles: String,
	/// How much of each principle to render into the output.
	#[arg(long, value_enum, default_value_t = Detail::Summary)]
	principle_detail: Detail,
	/// Print the default-selected principles (numbered) and exit, without scaffolding.
	#[arg(long)]
	list_principles: bool,
	/// Choose principles interactively in a two-pane selector, seeded from `--principles`.
	#[arg(long, short)]
	interactive: bool,
}

fn main() -> io::Result<()> {
	let cli = Cli::parse();

	let principles = pack::default_principles();
	let selected = match pack::resolve_selection(&principles, &cli.principles) {
		Ok(selected) => selected,
		Err(error) => {
			eprintln!("error: {error}");
			std::process::exit(2);
		}
	};

	if cli.list_principles {
		println!("{}", pack::render_principles(&selected, cli.principle_detail));
		return Ok(());
	}

	// Interactive selection overrides the resolved set, seeded from it. On
	// confirm it prints a `--principles` line so the exact selection and order
	// can be replayed non-interactively; on abort nothing is written.
	let selected = if cli.interactive {
		let initial: Vec<usize> = selected
			.iter()
			.map(|p| {
				principles
					.iter()
					.position(|q| q.id == p.id)
					.expect("selected principle is from the pack")
			})
			.collect();
		match tui::run_selection(&principles, &initial)? {
			Some(order) => {
				let chosen: Vec<&pack::Principle> = order.iter().map(|&i| &principles[i]).collect();
				let ids: Vec<&str> = chosen.iter().map(|p| p.id.as_str()).collect();
				println!("selection: --principles {}", ids.join(","));
				chosen
			}
			None => {
				eprintln!("aborted; nothing written");
				return Ok(());
			}
		}
	} else {
		selected
	};

	for (path, outcome) in scaffold(&cli.output_dir, &selected, cli.principle_detail, cli.force)? {
		println!("{:>16}  {}", outcome.label(), path);
	}
	Ok(())
}

#[cfg(test)]
mod tests {
	use super::*;

	/// A unique scratch directory under the system temp dir for one test.
	fn scratch(name: &str) -> PathBuf {
		let dir = std::env::temp_dir().join(format!(
			"agent-scaffold-poc-{}-{}",
			std::process::id(),
			name
		));
		let _ = fs::remove_dir_all(&dir);
		dir
	}

	#[test]
	fn first_run_creates_everything() {
		let root = scratch("first-run");
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();
		let results = scaffold(&root, &selected, Detail::Summary, false).unwrap();
		assert!(results.iter().all(|(_, o)| *o == Outcome::Created));
		assert!(root.join("AGENTS.md").exists());
		assert!(root.join(".agents/principles.toml").exists());
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn generated_agents_has_principles_and_no_placeholder() {
		let root = scratch("generated");
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();
		scaffold(&root, &selected, Detail::Summary, false).unwrap();
		let agents = fs::read_to_string(root.join("AGENTS.md")).unwrap();
		assert!(!agents.contains("{{principles}}"));
		assert!(agents.contains("1. "));
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn rerun_refreshes_reference_but_skips_working() {
		let root = scratch("rerun");
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();
		scaffold(&root, &selected, Detail::Summary, false).unwrap();

		// A user edits a working file after the first run.
		fs::write(root.join("AGENTS.md"), "user edits\n").unwrap();

		let results = scaffold(&root, &selected, Detail::Summary, false).unwrap();
		let outcome_of =
			|p: &str| results.iter().find(|(path, _)| *path == p).map(|(_, o)| o).unwrap();

		// Reference assets are refreshed; the edited working file is left alone.
		assert_eq!(*outcome_of(".agents/principles.toml"), Outcome::Refreshed);
		assert_eq!(*outcome_of("AGENTS.md"), Outcome::SkippedExisting);
		assert_eq!(fs::read_to_string(root.join("AGENTS.md")).unwrap(), "user edits\n");
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn force_overwrites_working_files() {
		let root = scratch("force");
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();
		scaffold(&root, &selected, Detail::Summary, false).unwrap();
		fs::write(root.join("AGENTS.md"), "user edits\n").unwrap();

		let results = scaffold(&root, &selected, Detail::Summary, true).unwrap();
		let agents = results.iter().find(|(path, _)| *path == "AGENTS.md").map(|(_, o)| o).unwrap();
		assert_eq!(*agents, Outcome::Overwritten);
		let contents = fs::read_to_string(root.join("AGENTS.md")).unwrap();
		assert_ne!(contents, "user edits\n");
		assert!(contents.starts_with("# Agent guidance"));
		fs::remove_dir_all(&root).unwrap();
	}
}
