//! agent-scaffold: scaffold the agent workflow into a project.
//!
//! Two-tier ownership from the spec:
//!
//! - Reference assets (tool-owned, under `.agents/`) are always refreshed.
//! - Working files (the root `AGENTS.md` and the plan template) are
//!   create-if-absent unless `--force`.
//!
//! `AGENTS.md` is generated by rendering the selected principles into the
//! pack's guidance template; the other assets are dropped verbatim.

mod checks;
mod manifest;
#[macro_use]
mod metrics;
mod pack;
mod plan;
mod tui;
mod workflow;
mod workflow_spec;

use {
	clap::{
		Args,
		Parser,
		Subcommand,
		ValueEnum,
	},
	manifest::{
		Asset,
		Ownership,
	},
	pack::Detail,
	serde::Serialize,
	std::{
		collections::{
			BTreeMap,
			HashMap,
		},
		fs,
		io::{
			self,
			IsTerminal,
		},
		path::{
			Path,
			PathBuf,
		},
	},
};

/// What happened to a single asset on a scaffold run.
#[derive(Debug, PartialEq, Eq)]
enum Outcome {
	Created,
	Refreshed,
	SkippedExisting,
	Overwritten,
}

impl Outcome {
	/// Present-tense label for the plan preview: what the action would do.
	fn plan_label(&self) -> &'static str {
		match self {
			Outcome::Created => "create",
			Outcome::Refreshed => "refresh",
			Outcome::SkippedExisting => "skip (exists)",
			Outcome::Overwritten => "overwrite",
		}
	}
}

/// Decide, without touching the filesystem, what would happen to `asset` under
/// `root`. This drives the dry-run preview, so it must not write.
fn outcome_of(
	root: &Path,
	asset: &Asset,
	force: bool,
) -> Outcome {
	let exists = root.join(&asset.dest).exists();
	match asset.ownership {
		Ownership::Reference =>
			if exists {
				Outcome::Refreshed
			} else {
				Outcome::Created
			},
		Ownership::Working =>
			if exists {
				if force { Outcome::Overwritten } else { Outcome::SkippedExisting }
			} else {
				Outcome::Created
			},
	}
}

/// Write `asset` under `root`, unless the planned outcome is to skip it. An asset
/// marked executable in the manifest (for example the checks module's
/// `.agents/hooks/pre-commit`) has its executable bit set after the write.
fn apply_asset(
	root: &Path,
	asset: &Asset,
	outcome: &Outcome,
) -> io::Result<()> {
	if matches!(outcome, Outcome::SkippedExisting) {
		return Ok(());
	}
	let dest = root.join(&asset.dest);
	if let Some(parent) = dest.parent() {
		fs::create_dir_all(parent)?;
	}
	fs::write(&dest, &asset.contents)?;
	if asset.executable {
		make_executable(&dest)?;
	}
	Ok(())
}

/// Set the executable bit on `path` (mode `0o755`) on Unix; a no-op elsewhere.
/// Used both for executable scaffolded assets and for the installed pre-commit
/// hook, so the two share one implementation.
#[cfg(unix)]
fn make_executable(path: &Path) -> io::Result<()> {
	use std::os::unix::fs::PermissionsExt;
	let mut perms = fs::metadata(path)?.permissions();
	perms.set_mode(0o755);
	fs::set_permissions(path, perms)
}

/// The non-Unix stand-in: file permissions are not modelled the same way, so the
/// executable bit is simply not set (a documented platform limitation).
#[cfg(not(unix))]
fn make_executable(_path: &Path) -> io::Result<()> {
	Ok(())
}

/// Version-control system to initialise in the output directory. Git by default;
/// `none` skips it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, ValueEnum)]
enum Vcs {
	/// Initialise a git repository (the default).
	Git,
	/// Do not initialise any repository.
	None,
}

/// The planned VCS action, decided from a read only (drives the preview, so it
/// must not write).
#[derive(Debug, PartialEq, Eq)]
enum InitPlan {
	/// No repository is initialised (`--vcs none`).
	None,
	/// The output directory is already inside a repository; skip it.
	SkipExists,
	/// Initialise a new git repository.
	Init,
}

/// Whether `dir` is already inside a git repository (a `.git` entry at `dir` or
/// any ancestor), in which case a new repository would nest and must be skipped.
/// A relative `dir` is resolved against the current directory so an enclosing
/// repository is found even when scaffolding into a subdirectory.
fn inside_git_repo(dir: &Path) -> io::Result<bool> {
	let absolute =
		if dir.is_absolute() { dir.to_path_buf() } else { std::env::current_dir()?.join(dir) };
	Ok(absolute.ancestors().any(|ancestor| ancestor.join(".git").exists()))
}

/// Decide the VCS action without writing: git (the default) initialises a
/// repository unless the output directory is already inside one; `none` skips.
fn init_plan(
	vcs: Vcs,
	output_dir: &Path,
) -> io::Result<InitPlan> {
	Ok(match vcs {
		Vcs::None => InitPlan::None,
		Vcs::Git =>
			if inside_git_repo(output_dir)? {
				InitPlan::SkipExists
			} else {
				InitPlan::Init
			},
	})
}

/// Initialise a git repository in `dir` by shelling out to `git init`. Exits 2
/// if the `git` binary is not installed.
fn run_git_init(dir: &Path) -> io::Result<()> {
	// `git init <dir>` creates the directory if it does not exist.
	match std::process::Command::new("git")
		.arg("init")
		.arg(dir)
		.stdout(std::process::Stdio::null())
		.status()
	{
		Ok(status) if status.success() => Ok(()),
		Ok(status) => {
			eprintln!("error: `git init` failed ({status})");
			std::process::exit(2);
		}
		Err(error) if error.kind() == io::ErrorKind::NotFound => {
			eprintln!(
				"error: initialising a git repository needs the `git` binary, which was not found; \
				 pass `--vcs none` to skip"
			);
			std::process::exit(2);
		}
		Err(error) => Err(error),
	}
}

/// The active pack's principle set: parse its `principles.toml`, or an empty set
/// when the pack ships none. A malformed `principles.toml` is a parse error. For
/// the built-in pack this reads the same embedded file the drop uses, so the
/// selection and the dropped `principles.toml` stay consistent.
fn pack_principles(source: &manifest::PackSource) -> Result<Vec<pack::Principle>, toml::de::Error> {
	match source.read("principles.toml") {
		Ok(toml) => pack::parse_principles(&toml),
		// A pack that ships no principles.toml simply has no principles to select.
		Err(_) => Ok(Vec::new()),
	}
}

/// Build the asset set to drop from the active pack: `{{principles}}` is
/// rendered from the current selection, `{{instrument}}` is the pack's
/// `instrument.md` fragment when `instrument` is set (empty otherwise, or when
/// the pack ships no such fragment), `overrides` supplies the `--var` values for
/// any variables the pack declares, and `modules` are the `--module` selections
/// whose tagged assets are included (core assets always are) and whose guidance
/// partials fill the reserved `{{modules}}` slot (empty when none is enabled).
/// Building does not write.
fn build_assets(
	source: &manifest::PackSource,
	selected: &[&pack::Principle],
	detail: Detail,
	overrides: &HashMap<String, String>,
	instrument: bool,
	modules: &[String],
) -> Result<Vec<Asset>, manifest::LoadError> {
	let mut builtin: HashMap<String, String> = HashMap::new();
	builtin.insert("principles".to_string(), pack::render_principles(selected, detail));
	// A pack that ships no instrument.md renders nothing, exactly as a pack
	// without principles.toml renders no principles.
	let instrument_block =
		if instrument { source.read("instrument.md").unwrap_or_default() } else { String::new() };
	builtin.insert("instrument".to_string(), instrument_block);
	// The `{{modules}}` block: the concatenated guidance partials of the enabled
	// modules (the `--module` selections closed under `requires`). Empty when no
	// module is enabled, so a pack with no modules (the built-in one) leaves the
	// rendered output byte-identical.
	let modules_block = manifest::module_guidance(source, modules)?;
	builtin.insert("modules".to_string(), modules_block);
	manifest::load(source, &builtin, overrides, modules)
}

/// Whether the two-pane selector should open: only on a real terminal (both
/// input and output), when there is something to select, and when neither
/// `--write` nor `--dry-run` has asked for a non-interactive run.
fn use_selector(
	args: &ScaffoldArgs,
	principles: &[pack::Principle],
) -> bool {
	!args.write
		&& !args.dry_run
		&& !principles.is_empty()
		&& io::stdin().is_terminal()
		&& io::stdout().is_terminal()
}

/// Build and write the asset set, returning each asset's path and outcome. A
/// convenience for tests; `main` drives build, plan, and apply separately so it
/// can preview and confirm before writing.
#[cfg(test)]
fn scaffold(
	source: &manifest::PackSource,
	root: &Path,
	selected: &[&pack::Principle],
	detail: Detail,
	overrides: &HashMap<String, String>,
	force: bool,
	instrument: bool,
) -> Result<Vec<(String, Outcome)>, manifest::LoadError> {
	build_assets(source, selected, detail, overrides, instrument, &[])?
		.into_iter()
		.map(|asset| {
			let outcome = outcome_of(root, &asset, force);
			apply_asset(root, &asset, &outcome).map(|()| (asset.dest, outcome))
		})
		.collect::<io::Result<Vec<_>>>()
		.map_err(manifest::LoadError::from)
}

/// Top-level CLI: every action is a subcommand. Bare invocation prints the
/// subcommand list (`arg_required_else_help`), so a newcomer discovers the
/// surface rather than triggering a default action.
#[derive(Parser)]
#[command(
	name = "agent-scaffold",
	version,
	about = "Scaffold the agent workflow into a project, and validate or project its state.",
	arg_required_else_help = true
)]
struct Cli {
	#[command(subcommand)]
	command: Command,
}

/// The available actions, one per verb.
#[derive(Subcommand)]
enum Command {
	/// Scaffold the agent workflow into a project. On a terminal the principle selector opens unless --write or --dry-run is given.
	Scaffold(ScaffoldArgs),
	/// Validate the workflow's metrics log against the record schema, (with --plan) the plan's structured regions, and (with --workflow) the plan status against the round log; exits non-zero on any violation.
	Validate(ValidateArgs),
	/// Project the workflow state: emit a derived summary of the plan's Roadmap steps and open questions plus a metrics-record count. Best-effort; a missing file yields a partial projection.
	Status(StatusArgs),
	/// Run the project's `.agents/checks.toml` lint and format checks in a temporary, isolated git worktree of the current tracked working-tree state, so a relative-path check cannot mutate the live tree (this is isolation, not a security sandbox: a check that writes an absolute path or mutates git metadata is trusted-config self-harm and out of contract). Exits 0 iff every check that ran passed.
	Checks(ChecksArgs),
	/// Render a `<task>.plan.toml` skeleton plus its Markdown sidecars into the generated `<task>.md`. Strict: a schema violation, an unresolved cross-reference, or a missing sidecar exits non-zero and writes nothing. With --check, re-render in memory and compare against the committed `<task>.md` without writing (warn on mismatch by default; --strict exits non-zero on mismatch, for CI or a pre-commit hook).
	Render(RenderArgs),
}

/// Arguments for the `scaffold` subcommand.
#[derive(Args)]
struct ScaffoldArgs {
	/// Directory to scaffold into (defaults to the current directory).
	#[arg(long, default_value = ".")]
	output_dir: PathBuf,
	/// Overwrite existing user working files instead of leaving them untouched.
	#[arg(long)]
	force: bool,
	/// Version-control system to initialise in the output directory (git by default; use `none` to skip).
	#[arg(long, value_enum, default_value_t = Vcs::Git)]
	vcs: Vcs,
	/// Apply the changes non-interactively, without the selector. Off a terminal, writes need this flag.
	#[arg(long)]
	write: bool,
	/// Preview the plan and exit without writing and without opening the selector.
	#[arg(long, conflicts_with = "write")]
	dry_run: bool,
	/// Which principles to include: default, all, none, or a comma-separated list of ids.
	#[arg(long, default_value = "default")]
	principles: String,
	/// How much of each principle to render into the output.
	#[arg(long, value_enum, default_value_t = Detail::Summary)]
	principle_detail: Detail,
	/// Print the default-selected principles (numbered) and exit, without scaffolding.
	#[arg(long)]
	list_principles: bool,
	/// Scaffold from a user-supplied pack directory instead of the built-in one.
	#[arg(long)]
	template: Option<PathBuf>,
	/// Set a pack-declared variable, as `--var key=value` (repeatable).
	#[arg(long = "var", value_name = "KEY=VALUE")]
	var: Vec<String>,
	/// Include an optional module's assets, as `--module <name>` (repeatable). Unknown modules are an error.
	#[arg(long = "module", value_name = "NAME")]
	modules: Vec<String>,
	/// Include opt-in workflow instrumentation: render calibration-logging
	/// instructions into the guidance so the workflow records metrics to
	/// `docs/metrics/workflow.jsonl`. Off by default.
	#[arg(long)]
	instrument: bool,
	/// Install a git pre-commit hook that runs the checks gate, create-if-absent (never clobbering an existing hook). Meaningful only with `--module checks`; using it without that module is a usage error. The installed hook delegates to the scaffolded `.agents/hooks/pre-commit`.
	#[arg(long)]
	with_precommit_hook: bool,
}

/// Arguments for the `validate` subcommand.
#[derive(Args)]
struct ValidateArgs {
	/// Path to the JSONL metrics log to validate.
	#[arg(long, default_value = "docs/metrics/workflow.jsonl")]
	metrics: PathBuf,
	/// Path to a Markdown plan to validate (its Roadmap and Open Questions regions). When omitted, only the metrics log is validated.
	#[arg(long)]
	plan: Option<PathBuf>,
	/// Path to a `<task>.plan.toml` structured source to validate (its schema and internal cross-references). When omitted, no source is validated. When it declares `[meta].primary = "toml"`, it also drives the --workflow check (its steps, questions, waivers, and baseline) instead of the Markdown --plan.
	#[arg(long)]
	source: Option<PathBuf>,
	/// Cross-reference the plan's Roadmap status against the round log (the workflow invariants): every `complete` step must have converged round records. Reads the plan from a TOML source (via --source) when it declares `[meta].primary = "toml"`, else from the Markdown --plan; the round log comes from --metrics (which defaults). A TOML-primary --source needs no --plan (a TOML-only project has no Markdown plan); the Markdown path still needs --plan present. Requesting --workflow with neither a TOML-primary --source nor a --plan is an error.
	#[arg(long)]
	workflow: bool,
	/// Path to a `workflow.toml` control-constants spec supplying the convergence streaks, round cap, and backstop severity the --workflow check reads. When omitted, the built-in default (today's constants) is used, so the check is unchanged. A malformed spec is a hard error (non-zero exit). Requires --workflow (the flag is meaningless without it, and would otherwise leave a malformed spec unparsed and exit 0).
	#[arg(long, requires = "workflow")]
	workflow_spec: Option<PathBuf>,
}

/// Arguments for the `status` subcommand.
#[derive(Args)]
struct StatusArgs {
	/// Path to a Markdown plan to project (its Roadmap steps and Open Questions items). When omitted, the plan part of the projection is empty.
	#[arg(long)]
	plan: Option<PathBuf>,
	/// Path to a `<task>.plan.toml` structured source. When it declares `[meta].primary = "toml"`, the plan projection is read from it instead of --plan (else --plan is used, so a Markdown-primary or absent source is unaffected).
	#[arg(long)]
	source: Option<PathBuf>,
	/// Path to the JSONL metrics log to summarise (a record count).
	#[arg(long, default_value = "docs/metrics/workflow.jsonl")]
	metrics: PathBuf,
	/// Emit the projection as JSON instead of a short human-readable summary.
	#[arg(long)]
	json: bool,
}

/// Arguments for the `render` subcommand.
#[derive(Args)]
struct RenderArgs {
	/// Path to the `<task>.plan.toml` skeleton to render. Its sidecars are resolved relative to its directory, and the output is `<task>.md` beside it.
	plan: PathBuf,
	/// Re-render in memory and compare against the committed `<task>.md` instead of writing it. Warns on a mismatch by default (exit 0); pair with --strict to fail.
	#[arg(long)]
	check: bool,
	/// With --check, exit non-zero on a mismatch (for CI or a pre-commit hook) rather than only warning. Meaningless without --check.
	#[arg(long, requires = "check")]
	strict: bool,
}

/// Arguments for the `checks` subcommand.
#[derive(Args)]
struct ChecksArgs {
	/// The project root to check (defaults to the current directory). Its `.agents/checks.toml` is read, and the checks run in a temporary worktree of this repository.
	#[arg(long, default_value = ".")]
	dir: PathBuf,
	/// Isolate the STAGED (index) content instead of the working tree, so the run checks exactly what a commit would record (what the pre-commit hook uses). Without it, the working-tree state is isolated.
	#[arg(long)]
	staged: bool,
}

/// A derived, best-effort projection of the workflow state, serialised by
/// `status`. Every part is optional so a missing plan or metrics file yields a
/// partial projection rather than a failure; nothing here is a source of truth
/// (it is regenerable from the plan and the metrics log).
#[derive(Serialize)]
struct Projection {
	/// The plan projection, present only when a readable `--plan` was given.
	plan: Option<PlanProjection>,
	/// The metrics summary, present only when the metrics log exists.
	metrics: Option<MetricsProjection>,
}

/// The plan half of the projection: the Roadmap steps and the Open Questions
/// items, as parsed from the plan's structured regions.
#[derive(Serialize)]
struct PlanProjection {
	/// The Roadmap steps (slug plus status), in table order.
	steps: Vec<plan::Step>,
	/// The Open Questions queue items (id, status, ask), in list order.
	open_questions: Vec<plan::Question>,
}

/// The metrics half of the projection: a small summary of the metrics log.
#[derive(Serialize)]
struct MetricsProjection {
	/// The number of records (non-blank lines) in the metrics log.
	records: usize,
}

fn main() -> io::Result<()> {
	let cli = Cli::parse();
	match cli.command {
		Command::Scaffold(args) => run_scaffold(args),
		Command::Validate(args) => run_validate(args),
		Command::Status(args) => run_status(args),
		Command::Checks(args) => run_checks(args),
		Command::Render(args) => run_render(args),
	}
}

/// Render a `<task>.plan.toml` into its generated `<task>.md`, or (with `--check`)
/// compare a fresh render against the committed file without writing.
///
/// The render is STRICT and writes exactly one file: on any schema violation,
/// unresolved cross-reference, or missing sidecar it prints the problems to stderr
/// and exits 1, writing nothing (a broken source never yields a partial plan). A
/// successful `render` writes `<task>.md` beside the source.
///
/// `--check` re-renders in memory and byte-compares against the committed `<task>.md`
/// (the golden), catching both a hand-edit of the generated file and a stale render
/// after a source edit. Severity follows the shipped "warn loudly, fail hard only
/// when asked" stance: a mismatch is a stderr WARNING and exit 0 by default, and a
/// hard failure (exit 1) under `--strict` (for CI or the pre-commit hook). A render
/// failure under `--check` still exits 1, since there is no golden to check a broken
/// source against.
fn run_render(args: RenderArgs) -> io::Result<()> {
	if args.check {
		match plan::check_render(&args.plan) {
			Ok(plan::CheckOutcome::Match) => {
				println!("{}: up to date", args.plan.display());
				Ok(())
			}
			Ok(
				outcome @ plan::CheckOutcome::Mismatch {
					..
				},
			) => {
				let committed_exists = matches!(
					outcome,
					plan::CheckOutcome::Mismatch {
						committed_exists: true,
						..
					}
				);
				let out = plan::rendered_path(&args.plan)
					.map(|path| path.display().to_string())
					.unwrap_or_else(|_| "<task>.md".to_string());
				let detail = if committed_exists {
					let where_ = outcome
						.difference_summary()
						.map(|summary| format!(" ({summary})"))
						.unwrap_or_default();
					format!(
						"{out} differs from a fresh render (a hand-edit, or a stale render after a \
						 source edit){where_}"
					)
				} else {
					format!(
						"{out} does not exist; run `agent-scaffold render {}` to generate it",
						args.plan.display()
					)
				};
				if args.strict {
					eprintln!("error: {detail}");
					std::process::exit(1);
				} else {
					eprintln!(
						"warning: {detail}; re-render with `agent-scaffold render {}`",
						args.plan.display()
					);
					Ok(())
				}
			}
			Err(problems) => {
				for problem in &problems {
					eprintln!("{}: {problem}", args.plan.display());
				}
				std::process::exit(1);
			}
		}
	} else {
		match plan::render_plan(&args.plan) {
			Ok(rendered) => {
				let out = match plan::rendered_path(&args.plan) {
					Ok(path) => path,
					Err(problems) => {
						for problem in &problems {
							eprintln!("{}: {problem}", args.plan.display());
						}
						std::process::exit(1);
					}
				};
				plan::write_rendered(&out, &rendered)?;
				println!("rendered {}", out.display());
				Ok(())
			}
			Err(problems) => {
				for problem in &problems {
					eprintln!("{}: {problem}", args.plan.display());
				}
				std::process::exit(1);
			}
		}
	}
}

/// Run the project's checks under `args.dir`, isolated in a temporary git
/// worktree, and report per-check results. Exit codes follow the `validate`
/// family: 0 when every check that ran passed (or there was nothing to run), 1
/// when a check failed or the config was malformed, and 2 for an environment or
/// usage error (not a git repository, git or `sh` missing, an unreadable config,
/// the worktree setup failing). An absent `.agents/checks.toml` is a clear note
/// and exit 0, matching how `validate` treats an absent metrics log. The
/// isolation bounds mutation for a relative-path check; it is not a security
/// sandbox (see `checks` module docs).
fn run_checks(args: ChecksArgs) -> io::Result<()> {
	let mode = if args.staged { checks::Isolation::Staged } else { checks::Isolation::WorkingTree };
	let report = match checks::run(&args.dir, mode) {
		Ok(report) => report,
		Err(error) => {
			// The exit code is single-sourced on `RunError::exit_code`: a malformed
			// config is a project problem (exit 1), and every environment/usage error,
			// including an unreadable config (`Io`), is exit 2. The `Io` case must NOT
			// propagate through `io::Result` (that would exit 1 with a capital "Error:"),
			// so it goes through this branch like the others.
			eprintln!("error: {error}");
			std::process::exit(error.exit_code());
		}
	};

	if !report.config_present {
		// Written to stderr for parity with `validate`, whose absent-file notes are
		// stderr too (the stdout is reserved for the report proper).
		eprintln!(
			"no checks config at {}; nothing to run",
			args.dir.join(".agents").join("checks.toml").display()
		);
		return Ok(());
	}

	// Per-check lines, then a final summary. Passing and skipped checks go to stdout;
	// a failing check also prints its captured output to stderr so the evidence is
	// visible without being mistaken for normal output.
	let mut passed = 0usize;
	let mut failed = 0usize;
	let mut skipped = 0usize;
	for result in &report.results {
		match &result.status {
			checks::CheckStatus::Passed => {
				passed += 1;
				println!("{:>12}  {} ({})", "pass", result.name, result.kind.as_str());
			}
			checks::CheckStatus::Failed(output) => {
				failed += 1;
				println!("{:>12}  {} ({})", "fail", result.name, result.kind.as_str());
				eprintln!("--- {} ({}) output ---", result.name, result.kind.as_str());
				eprintln!("{output}");
			}
			checks::CheckStatus::Skipped(reason) => {
				skipped += 1;
				println!("{:>12}  {} ({}): {reason}", "skip", result.name, result.kind.as_str());
			}
		}
	}

	if report.ran_any() {
		println!("checks: {passed} passed, {failed} failed, {skipped} skipped");
	} else {
		println!("checks: nothing to run ({skipped} skipped)");
	}

	if report.success() {
		Ok(())
	} else {
		std::process::exit(1);
	}
}

/// Fold a workflow check's result into the run's summaries or problems, so the TOML-
/// sourced and Markdown-sourced branches report identically: an empty result is a
/// one-line "invariants hold" summary, and each violation is prefixed with the plan
/// source and the log it spans. Single-sourced so the two branches cannot drift.
fn report_workflow(
	workflow_problems: Vec<String>,
	source_display: &str,
	metrics_display: &str,
	summaries: &mut Vec<String>,
	problems: &mut Vec<String>,
) {
	if workflow_problems.is_empty() {
		summaries.push(format!("{source_display} vs {metrics_display}: workflow invariants hold"));
	} else {
		for problem in workflow_problems {
			problems.push(format!("{source_display} vs {metrics_display}: {problem}"));
		}
	}
}

/// Validate the metrics log at `args.metrics` against the record schema and, when
/// `--plan` is given, the plan's structured regions against the plan schema.
///
/// An absent file (the metrics log, or a `--plan` path) is not a validation
/// failure: not every project instruments, and a plan is validated only on
/// request, so a missing file prints a note to stderr and is skipped rather than
/// hard-failing (the same treatment for both, so the behaviour is consistent).
/// Every actual violation (a malformed metrics record, or a broken plan region)
/// is collected, prefixed with its file, and printed to stderr; if any exist the
/// run exits with code 1 (a validation failure, distinct from the code 2 used for
/// usage errors). Otherwise each present, valid file prints a one-line ok summary
/// and the run exits 0. With no `--plan` and no `--workflow`, this is metrics-only,
/// unchanged from the previous increment. With `--workflow` (which still requires
/// `--plan`), the plan status is cross-referenced against the round log: every
/// `complete` Roadmap step must have converged round records. When `--source` is
/// TOML-primary (`[meta].primary = "toml"`) the steps, questions, waivers, and
/// baseline are read from it instead of the Markdown plan (the Inc 4 swap); otherwise
/// the Markdown `--plan` is used. Either way the check needs the metrics log and the
/// chosen plan source present; if a needed file is absent it prints a note and is
/// skipped, the same treatment a missing file gets elsewhere here. `--plan` stays
/// clap-required for now (the relaxation for a TOML-only project is deferred).
///
/// In TOML-primary mode the Markdown `--plan` is a GENERATED projection (rendered from
/// the TOML, pinned to it by `render --check`), so the hand-authored-Markdown validator
/// (`validate_plan`) is NOT run against it; the TOML is validated instead by
/// `validate_source`. In Markdown mode `validate_plan` runs on `--plan` unchanged.
fn run_validate(args: ValidateArgs) -> io::Result<()> {
	let mut problems: Vec<String> = Vec::new();
	let mut summaries: Vec<String> = Vec::new();

	// Read each present file once and keep its contents, so the workflow check can
	// reuse them rather than reading twice.
	let metrics_path = &args.metrics;
	let metrics_contents = if metrics_path.exists() {
		let contents = fs::read_to_string(metrics_path)?;
		let errors = metrics::validate_log(&contents);
		if errors.is_empty() {
			summaries.push(format!(
				"{}: {} records, valid",
				metrics_path.display(),
				metrics::count_records(&contents)
			));
		} else {
			for error in &errors {
				problems.push(format!(
					"{}:{}: {}",
					metrics_path.display(),
					error.line,
					error.reason
				));
			}
		}
		Some(contents)
	} else {
		eprintln!("no metrics log at {}; nothing to validate", metrics_path.display());
		None
	};

	// The `<task>.plan.toml` structured source, validated on request (like --plan). An
	// absent --source path prints a note and is skipped, the same treatment the metrics
	// log and the plan get. When it declares `[meta].primary = "toml"` it ALSO becomes
	// the source the --workflow check reads below (the Inc 4 gate); a Markdown-primary
	// or unparseable source is validated but does not drive the workflow check.
	//
	// Read BEFORE the Markdown --plan because, in TOML-primary mode, it decides whether
	// --plan is validated at all (see `plan_is_projection` below).
	let source_plan: Option<plan::PlanToml> = if let Some(source_path) = &args.source {
		if source_path.exists() {
			let contents = fs::read_to_string(source_path)?;
			let source_problems = plan::validate_source(&contents);
			if source_problems.is_empty() {
				// A clean validate implies a clean parse, so the count is a re-parse of a
				// known-good source; fall back to a bare "valid" if that somehow disagrees.
				let summary = match plan::parse_toml(&contents) {
					Ok(parsed) => format!(
						"{}: {} steps, {} questions, valid",
						source_path.display(),
						parsed.steps.len(),
						parsed.questions.len()
					),
					Err(_) => format!("{}: valid", source_path.display()),
				};
				summaries.push(summary);
			} else {
				for problem in &source_problems {
					problems.push(format!("{}: {}", source_path.display(), problem));
				}
			}
			// Parse (independently of the validate outcome) so the workflow gate can read
			// it. A parse failure means "no TOML source" and the check falls back to the
			// Markdown plan; `validate_source` already reported the malformed source above.
			plan::parse_toml(&contents).ok()
		} else {
			eprintln!("no source plan at {}; nothing to validate", source_path.display());
			None
		}
	} else {
		None
	};

	// Whether the Markdown --plan is a GENERATED projection rather than a hand-authored
	// source: true exactly when the --source parses as a TOML-primary plan
	// (`[meta].primary = "toml"`). In that mode `<task>.md` is rendered FROM the TOML and
	// pinned to it by `render --check`, and the TOML itself is validated above by
	// `validate_source`, so running the hand-authored-Markdown validator (`validate_plan`)
	// against the projection is category-confused and is skipped. In Markdown mode (no
	// --source, a Markdown-primary source, or an unparseable one) `validate_plan` runs on
	// --plan exactly as before.
	let plan_is_projection = source_plan.as_ref().is_some_and(plan::PlanToml::is_toml_primary);

	let plan_contents = if let Some(plan_path) = &args.plan {
		if plan_path.exists() {
			let contents = fs::read_to_string(plan_path)?;
			if plan_is_projection {
				summaries.push(format!(
					"{}: generated projection of a TOML-primary source; skipping the Markdown plan \
					 validator",
					plan_path.display()
				));
			} else {
				let plan_problems = plan::validate_plan(&contents);
				if plan_problems.is_empty() {
					summaries.push(format!(
						"{}: {} steps, {} open-questions items, valid",
						plan_path.display(),
						plan::parse_roadmap(&contents).len(),
						plan::parse_questions(&contents).len()
					));
				} else {
					for problem in &plan_problems {
						problems.push(format!("{}: {}", plan_path.display(), problem));
					}
				}
			}
			Some(contents)
		} else {
			eprintln!("no plan at {}; nothing to validate", plan_path.display());
			None
		}
	} else {
		None
	};

	// The workflow cross-reference. When the --source is TOML-primary, the checks read
	// steps/questions/waivers from it and the baseline from `[meta].w4_baseline`, joining
	// the JSONL rounds/decisions/escalations (the Inc 4 swap); otherwise they read the
	// Markdown plan + the JSONL waiver/baseline records, unchanged. Problems are reported
	// into the same list, prefixed with the source and the log a violation spans.
	if args.workflow {
		// Resolve the workflow control-constants spec: the built-in default (today's
		// constants, so the check is byte-for-byte unchanged) unless --workflow-spec
		// points at a file to parse. A parse error is a hard input error (non-zero
		// exit), not a skipped check that would green-pass.
		let workflow_spec = match &args.workflow_spec {
			Some(path) => {
				let contents = fs::read_to_string(path)?;
				match workflow_spec::WorkflowSpec::parse(&contents) {
					Ok(spec) => spec,
					Err(error) => {
						eprintln!("{}: {error}", path.display());
						std::process::exit(1);
					}
				}
			}
			None => workflow_spec::WorkflowSpec::builtin(),
		};
		let toml_primary = source_plan.as_ref().filter(|source| source.is_toml_primary());
		match (toml_primary, &plan_contents, &metrics_contents) {
			// TOML-sourced: the plan is read from the TOML source, so `plan_contents` is
			// ignored here and no --plan is required (a TOML-only project has no Markdown
			// plan; the clap `requires` was relaxed for exactly this case). Needs the metrics
			// log for the rounds/decisions/escalations.
			(Some(source), _, Some(metrics_text)) => {
				let source_display = args
					.source
					.as_ref()
					.map_or_else(|| "source".to_string(), |path| path.display().to_string());
				report_workflow(
					workflow::check_workflow_toml(&workflow_spec, source, metrics_text),
					&source_display,
					&metrics_path.display().to_string(),
					&mut summaries,
					&mut problems,
				);
			}
			// Markdown-sourced: needs both the Markdown plan and the metrics log.
			(None, Some(plan_text), Some(metrics_text)) => {
				let plan_display = args
					.plan
					.as_ref()
					.map_or_else(|| "plan".to_string(), |path| path.display().to_string());
				report_workflow(
					workflow::check_workflow(&workflow_spec, plan_text, metrics_text),
					&plan_display,
					&metrics_path.display().to_string(),
					&mut summaries,
					&mut problems,
				);
			}
			// No usable plan source resolved: neither a TOML-primary --source nor a
			// readable --plan (a typo'd/missing --source, a Markdown-primary --source with
			// no --plan, or no source at all). --workflow was explicitly requested, so
			// skipping would green-pass while checking nothing; make it a hard problem
			// instead. Independent of the metrics log.
			(None, None, _) => problems.push(
				"--workflow requested but no plan source resolved: pass a TOML-primary --source or a Markdown --plan"
					.to_string(),
			),
			// A plan source is present but the metrics log is missing: keep the
			// pre-existing stderr skip (the rounds/decisions log is what is absent).
			_ => eprintln!(
				"--workflow has a plan source but the metrics log is missing; skipping the workflow check"
			),
		}
	}

	if problems.is_empty() {
		for summary in &summaries {
			println!("{summary}");
		}
		Ok(())
	} else {
		for problem in &problems {
			eprintln!("{problem}");
		}
		std::process::exit(1);
	}
}

/// Read a `<task>.plan.toml` at `path` and return it only when it is the plan's
/// source of truth (`[meta].primary == "toml"`), the Inc 4 (Q-46) gate for `status`.
/// A `None` path, a missing file, or a source whose `[meta].primary` is `markdown` all
/// yield `None`, so the caller falls back to the Markdown `--plan` and the live repo (no
/// TOML source, or a Markdown-primary one) is unaffected.
///
/// A source that FAILS to parse also yields `None`, but because the caller explicitly
/// passed `--source`, a one-line stderr note makes the fallback visible rather than
/// silent (Principle 12, fail loudly). It stays a note, not a hard error: `status` is a
/// best-effort projection, and `validate --source` is where a malformed source is
/// REPORTED as a failure with a non-zero exit.
fn toml_source(path: &Option<PathBuf>) -> io::Result<Option<plan::PlanToml>> {
	let Some(path) = path else {
		return Ok(None);
	};
	if !path.exists() {
		return Ok(None);
	}
	let contents = fs::read_to_string(path)?;
	Ok(match plan::parse_toml(&contents) {
		Ok(source) if source.is_toml_primary() => Some(source),
		// Parsed but Markdown-primary (or primary unset): a legitimate fallback to
		// `--plan`, documented on the `--source` help, so no note.
		Ok(_) => None,
		// Failed to parse: make the silent fallback visible with a note rather than
		// swallowing it, since the user explicitly asked for this source.
		Err(_) => {
			eprintln!(
				"note: --source {} did not parse as a `<task>.plan.toml`; projecting from --plan",
				path.display()
			);
			None
		}
	})
}

/// Emit a best-effort projection of the workflow state: from `--plan` (when given
/// and readable) the Roadmap steps and Open Questions items, and from the metrics
/// log (when present) a record count. Unlike `validate`, this never hard-fails on
/// a missing or malformed file; a missing plan or metrics file simply leaves that
/// part of the projection empty. With `--json` the projection is printed as
/// pretty JSON; otherwise a short human-readable summary is printed.
fn run_status(args: StatusArgs) -> io::Result<()> {
	// The Inc 4 gate: when a `--source` is a `<task>.plan.toml` declaring
	// `[meta].primary = "toml"`, project the plan from it; otherwise fall back to the
	// Markdown `--plan`, so a Markdown-primary or absent source is unaffected.
	let plan = if let Some(source) = toml_source(&args.source)? {
		Some(PlanProjection {
			steps: source.step_views(),
			open_questions: source.question_views(),
		})
	} else {
		match &args.plan {
			Some(path) if path.exists() => {
				let contents = fs::read_to_string(path)?;
				Some(PlanProjection {
					steps: plan::parse_roadmap(&contents),
					open_questions: plan::parse_questions(&contents),
				})
			}
			_ => None,
		}
	};
	let metrics = if args.metrics.exists() {
		let contents = fs::read_to_string(&args.metrics)?;
		Some(MetricsProjection {
			records: metrics::count_records(&contents),
		})
	} else {
		None
	};
	let projection = Projection {
		plan,
		metrics,
	};

	if args.json {
		let json = serde_json::to_string_pretty(&projection).map_err(io::Error::other)?;
		println!("{json}");
	} else {
		match &projection.plan {
			Some(plan) => {
				// Group the steps by status so the summary is a few lines, not one per step.
				let mut by_status: BTreeMap<&str, usize> = BTreeMap::new();
				for step in &plan.steps {
					*by_status.entry(step.status.as_str()).or_default() += 1;
				}
				let breakdown: Vec<String> =
					by_status.iter().map(|(status, count)| format!("{count} {status}")).collect();
				println!(
					"plan: {} steps ({}); {} open-questions items",
					plan.steps.len(),
					breakdown.join(", "),
					plan.open_questions.len()
				);
			}
			None => println!("plan: not provided"),
		}
		match &projection.metrics {
			Some(metrics) => println!("metrics: {} records", metrics.records),
			None => println!("metrics: no log found"),
		}
	}
	Ok(())
}

/// The module name whose gate the pre-commit hook runs. `--with-precommit-hook` is
/// meaningful only when this module is selected.
const CHECKS_MODULE: &str = "checks";

/// The delegating pre-commit hook `--with-precommit-hook` installs into
/// `.git/hooks/pre-commit`. It execs the scaffolded, tracked
/// `.agents/hooks/pre-commit`, so the real logic lives in that one asset and never
/// drifts (one source of truth). `git rev-parse --show-toplevel` resolves the repo
/// root at hook-run time, so the hook works from any subdirectory.
const PRECOMMIT_DELEGATE: &str = "#!/bin/sh\n\
	# Installed by `agent-scaffold scaffold --with-precommit-hook` (create-if-absent).\n\
	# Delegates to the tracked, single-source hook so the real logic lives in one\n\
	# place and never drifts. Remove this file to disable the checks commit gate.\n\
	exec \"$(git rev-parse --show-toplevel)/.agents/hooks/pre-commit\"\n";

/// Whether the `--with-precommit-hook` request is coherent: it is meaningful only
/// alongside `--module checks`, so requesting it without that module is a usage
/// error (Principle 5, do not admit the incoherent state). Not requesting the hook
/// is always coherent.
fn precommit_coherent(
	with_hook: bool,
	modules: &[String],
) -> bool {
	!with_hook || modules.iter().any(|module| module == CHECKS_MODULE)
}

/// What happened when installing the pre-commit hook into `.git/hooks`.
#[derive(Debug, PartialEq, Eq)]
enum HookInstall {
	/// The hook was written (no prior hook existed); carries its path.
	Installed(PathBuf),
	/// A pre-commit hook entry already existed; it was left untouched (never
	/// clobbered). Carries the existing entry's path.
	Exists(PathBuf),
	/// The install was skipped rather than erroring the whole scaffold; carries a
	/// human-readable reason. Covers a non-repo output dir, a bare repository (whose
	/// delegating hook would be inert), and a filesystem error creating the hooks
	/// directory or writing the hook. The scaffolded assets already landed, so a
	/// hook-install problem must not fail the scaffold.
	Skipped(String),
}

/// Resolve the git hooks directory for `output_dir` via `git rev-parse --git-path
/// hooks`, which handles a `.git` directory, a `.git` file (a linked worktree or a
/// submodule), and honours the real git dir. Returns `None` when the directory is
/// not a git repository or `git` is unavailable, so the caller can skip the install
/// with a clear note instead of failing.
fn hooks_dir(output_dir: &Path) -> Option<PathBuf> {
	let output = std::process::Command::new("git")
		.arg("-C")
		.arg(output_dir)
		.args(["rev-parse", "--git-path", "hooks"])
		.output()
		.ok()?;
	if !output.status.success() {
		return None;
	}
	let rel = String::from_utf8_lossy(&output.stdout).trim().to_string();
	if rel.is_empty() {
		return None;
	}
	// `git -C <dir>` runs with `<dir>` as its working directory, so a relative path
	// it prints is relative to `output_dir`; make it absolute against that.
	let path = PathBuf::from(&rel);
	Some(if path.is_absolute() { path } else { output_dir.join(path) })
}

/// Whether `output_dir` is a bare git repository (no working tree). A bare repo has
/// a hooks directory, but the delegating hook resolves `git rev-parse
/// --show-toplevel`, which has no answer there, so an installed hook would be inert;
/// the caller skips it rather than installing a broken hook. A `git` failure is
/// treated as "not bare" (the caller's other guards still apply).
fn is_bare_repo(output_dir: &Path) -> bool {
	std::process::Command::new("git")
		.arg("-C")
		.arg(output_dir)
		.args(["rev-parse", "--is-bare-repository"])
		.output()
		.is_ok_and(|output| {
			output.status.success() && String::from_utf8_lossy(&output.stdout).trim() == "true"
		})
}

/// Canonicalise `path`, or its nearest existing ancestor when `path` itself does
/// not exist yet. The resolved hooks directory may not exist at check time (git
/// creates `.git/hooks` lazily, and a custom `core.hooksPath` may not be created
/// yet), so canonicalising the nearest existing ancestor still yields a real,
/// symlink-resolved absolute path to compare against. Returns `None` only when not
/// even the filesystem root resolves.
fn canonical_existing_ancestor(path: &Path) -> Option<PathBuf> {
	let mut current = Some(path);
	while let Some(candidate) = current {
		if let Ok(canonical) = candidate.canonicalize() {
			return Some(canonical);
		}
		current = candidate.parent();
	}
	None
}

/// Whether the resolved git `hooks` directory lands INSIDE `output_dir`. This is
/// the general escape guard for the hook install, on the actual invariant (the hook
/// must land inside the scaffolded project). Both paths are canonicalised (the hooks
/// dir via its nearest existing ancestor), so the check is a real path-prefix test
/// on symlink-resolved absolute paths, not a string compare. It rejects EVERY way
/// the resolved hooks dir can point outside `output_dir`:
/// - an ancestor-subdir scaffold, whose hooks dir is in the ancestor repo's `.git`;
/// - a LINKED WORKTREE, whose hooks are shared in the main repo's `.git` (its
///   `--show-toplevel` equals `output_dir`, so a toplevel-equality check would miss
///   it, but its hooks dir is outside `output_dir`);
/// - any other resolution (for example a `.git` gitdir pointer) that escapes.
///
/// A custom `core.hooksPath` INSIDE `output_dir` still passes and installs.
fn hooks_dir_inside_output(
	hooks: &Path,
	output_dir: &Path,
) -> bool {
	match (canonical_existing_ancestor(hooks), output_dir.canonicalize().ok()) {
		(Some(hooks_real), Some(output_real)) => hooks_real.starts_with(&output_real),
		_ => false,
	}
}

/// Where the pre-commit hook would be installed, or why it would be skipped,
/// resolved WITHOUT writing. Single-sources the install guards so the plan preview
/// and the actual install agree (Principle 16): both call this, so the preview can
/// never promise an install the write path then skips, or vice versa.
enum HookTarget {
	/// The hooks dir resolved inside `output_dir`; carries the `pre-commit` path.
	Inside(PathBuf),
	/// The install would be skipped; carries a human-readable reason.
	Skip(String),
}

/// Resolve the hook install target for `output_dir` (or the skip reason), without
/// writing. Skips a non-repo output dir, a bare repo (whose delegating hook, which
/// resolves `git rev-parse --show-toplevel`, would be inert), and any resolution
/// whose hooks dir lands OUTSIDE `output_dir` (see `hooks_dir_inside_output`).
fn resolve_hook_target(output_dir: &Path) -> HookTarget {
	let Some(hooks) = hooks_dir(output_dir) else {
		return HookTarget::Skip(format!("{} is not a git repository", output_dir.display()));
	};
	if is_bare_repo(output_dir) {
		return HookTarget::Skip(format!(
			"{} is a bare git repository (no working tree for the hook to check)",
			output_dir.display()
		));
	}
	if !hooks_dir_inside_output(&hooks, output_dir) {
		return HookTarget::Skip(format!(
			"the resolved git hooks directory ({}) is outside {} (a subdirectory of another repo, \
			 or a linked worktree sharing another repo's hooks); the hook was not installed there",
			hooks.display(),
			output_dir.display()
		));
	}
	HookTarget::Inside(hooks.join("pre-commit"))
}

/// Install the delegating pre-commit hook into the resolved hooks directory,
/// CREATE-IF-ABSENT: it writes the hook only when no entry exists, never clobbering
/// an existing hook (Principle 3). The written hook is made executable. Any problem
/// is reported as `Skipped` rather than failing, since the scaffolded assets already
/// landed: a non-repo output dir, a bare repo, a hooks dir that resolves OUTSIDE
/// `output_dir` (see `resolve_hook_target` / `hooks_dir_inside_output`), or a
/// filesystem error. This writes INTO the git dir, so it is deliberately separate
/// from the asset-drop path.
///
/// The escape guard matters: `git rev-parse --git-path hooks` can resolve to ANOTHER
/// repository's hooks, walking up to an ancestor repo's `.git` for a subdirectory
/// scaffold, or to the shared main `.git` for a linked worktree. Installing there
/// would drop a hook OUTSIDE `output_dir` (and a broken one, since the delegate
/// targets `<output_dir>/.agents/hooks/pre-commit`, which is not that other repo's),
/// blocking commits in it. The guard installs only when the resolved hooks dir is
/// inside `output_dir`.
///
/// Presence is tested with `symlink_metadata` (lstat), which does NOT follow
/// symlinks: a regular file, a valid symlink, AND a DANGLING symlink all count as
/// present and are left untouched. `Path::exists` follows links, so a dangling
/// symlink would read as absent and `fs::write` would then write the delegate
/// content THROUGH the symlink to a path outside the hooks directory, both
/// clobbering the user's intent and escaping the hooks directory. lstat closes that
/// hole.
fn install_precommit_hook(output_dir: &Path) -> HookInstall {
	let hook = match resolve_hook_target(output_dir) {
		HookTarget::Inside(hook) => hook,
		HookTarget::Skip(reason) => return HookInstall::Skipped(reason),
	};
	if let Some(parent) = hook.parent() {
		if let Err(error) = fs::create_dir_all(parent) {
			return HookInstall::Skipped(format!("could not create {}: {error}", parent.display()));
		}
	}
	// lstat, not `exists()`: leave ANY existing entry untouched, including a dangling
	// symlink (see the doc comment above for why `exists()` would be unsafe here).
	if hook.symlink_metadata().is_ok() {
		return HookInstall::Exists(hook);
	}
	if let Err(error) = fs::write(&hook, PRECOMMIT_DELEGATE) {
		return HookInstall::Skipped(format!("could not write {}: {error}", hook.display()));
	}
	if let Err(error) = make_executable(&hook) {
		return HookInstall::Skipped(format!(
			"could not set the executable bit on {}: {error}",
			hook.display()
		));
	}
	HookInstall::Installed(hook)
}

/// Print the manual activation one-liner for the scaffolded hook, used when an
/// existing hook is left in place or the install was skipped. The "check for an
/// existing hook first" caveat lives in the checks guidance, not here: it is
/// redundant in the already-exists path (we just reported one exists).
fn print_manual_hook_instructions() {
	eprintln!("To activate the scaffolded checks hook manually, from the repo root:");
	eprintln!("  ln -s ../../.agents/hooks/pre-commit .git/hooks/pre-commit");
}

fn run_scaffold(args: ScaffoldArgs) -> io::Result<()> {
	// `--with-precommit-hook` is meaningful only with `--module checks`; reject the
	// incoherent combination up front with a usage error (exit 2) before any work,
	// rather than admitting the bad state (Principle 5).
	if !precommit_coherent(args.with_precommit_hook, &args.modules) {
		eprintln!(
			"error: --with-precommit-hook requires --module checks (the hook runs the checks \
			 module's gate)"
		);
		std::process::exit(2);
	}

	// The active pack: the built-in one, or an external directory via --template.
	let source = match &args.template {
		Some(path) => manifest::PackSource::Directory(path.clone()),
		None => manifest::builtin(),
	};

	// Parse --var key=value overrides. Validation against the pack's declared
	// variables happens in the loader; here we only reject malformed entries.
	let mut overrides: HashMap<String, String> = HashMap::new();
	for entry in &args.var {
		match entry.split_once('=') {
			Some((key, value)) => {
				overrides.insert(key.to_string(), value.to_string());
			}
			None => {
				eprintln!("error: --var expects key=value, got `{entry}`");
				std::process::exit(2);
			}
		}
	}

	// Principles are a property of the active pack: the built-in set, or the
	// external pack's own principles.toml under --template.
	let principles = match pack_principles(&source) {
		Ok(principles) => principles,
		Err(error) => {
			eprintln!("error: could not parse the pack's principles.toml: {error}");
			std::process::exit(2);
		}
	};
	let selected = match pack::resolve_selection(&principles, &args.principles) {
		Ok(selected) => selected,
		Err(error) => {
			eprintln!("error: {error}");
			std::process::exit(2);
		}
	};

	if args.list_principles {
		println!("{}", pack::render_principles(&selected, args.principle_detail));
		return Ok(());
	}

	// On a terminal the selector opens by default: its Save modal is the write
	// confirmation, so Save both records the selection and means "write". --write
	// and --dry-run take the non-interactive path instead. On abort, nothing is
	// written.
	let (selected, write) = if use_selector(&args, &principles) {
		let initial: Vec<usize> = selected
			.iter()
			.map(|p| {
				principles
					.iter()
					.position(|q| q.id == p.id)
					.expect("selected principle is from the pack")
			})
			.collect();
		let save_summary = vec![
			format!("Scaffold into: {}", args.output_dir.display()),
			"Creates AGENTS.md and the docs/plans/ plan template if absent;".to_string(),
			"always refreshes the .agents/ reference assets.".to_string(),
			if args.force {
				"Existing working files WILL be overwritten (--force).".to_string()
			} else {
				"Existing working files are left untouched.".to_string()
			},
		];
		match tui::run_selection(&principles, &initial, save_summary)? {
			Some(order) => {
				let chosen: Vec<&pack::Principle> = order.iter().map(|&i| &principles[i]).collect();
				let ids: Vec<&str> = chosen.iter().map(|p| p.id.as_str()).collect();
				println!("selection: --principles {}", ids.join(","));
				(chosen, true)
			}
			None => {
				eprintln!("aborted; nothing written");
				return Ok(());
			}
		}
	} else {
		// Non-interactive: apply only when --write was given.
		(selected, args.write)
	};

	let assets = match build_assets(
		&source,
		&selected,
		args.principle_detail,
		&overrides,
		args.instrument,
		&args.modules,
	) {
		Ok(assets) => assets,
		Err(error) => {
			eprintln!("error: {error}");
			std::process::exit(2);
		}
	};
	let outcomes: Vec<Outcome> =
		assets.iter().map(|asset| outcome_of(&args.output_dir, asset, args.force)).collect();
	let repo = init_plan(args.vcs, &args.output_dir)?;

	// Always show the plan, then write only if confirmed. The repository line, if
	// any, comes first: the repo is initialised before the assets are dropped.
	match repo {
		InitPlan::Init => println!("{:>16}  git repository", "init"),
		InitPlan::SkipExists => println!("{:>16}  git repository", "skip (exists)"),
		InitPlan::None => {}
	}
	for (asset, outcome) in assets.iter().zip(&outcomes) {
		println!("{:>16}  {}", outcome.plan_label(), asset.dest);
	}
	// The pre-commit hook install is not a normal asset (it writes into the git dir),
	// so it is previewed on its own line, without asserting a fixed path (the real
	// hooks path can differ under a custom `core.hooksPath`). For an EXISTING repo the
	// preview is driven by the SAME `resolve_hook_target` predicate the install uses,
	// so preview and action agree exactly. For `InitPlan::Init` the repo does not
	// exist yet, so its hooks dir cannot be resolved here: a fresh repo uses
	// `.git/hooks` inside the output dir UNLESS it inherits an external
	// `core.hooksPath` (global or system) that resolves outside, in which case the
	// action correctly skips. The Init label is therefore CONDITIONAL so it never
	// promises a definite install the action might then skip. The post-write report
	// prints the actual resolved path or the skip reason.
	if args.with_precommit_hook {
		match repo {
			InitPlan::Init => println!(
				"{:>16}  pre-commit hook (create-if-absent, if the new repo's hooks dir is inside \
				 the project)",
				"install"
			),
			InitPlan::SkipExists | InitPlan::None =>
				if matches!(resolve_hook_target(&args.output_dir), HookTarget::Inside(_)) {
					println!("{:>16}  pre-commit hook (create-if-absent)", "install");
				} else {
					println!(
						"{:>16}  pre-commit hook (resolved hooks dir is outside the output dir)",
						"skip"
					);
				},
		}
	}

	if write {
		if matches!(repo, InitPlan::Init) {
			run_git_init(&args.output_dir)?;
		}
		for (asset, outcome) in assets.iter().zip(&outcomes) {
			apply_asset(&args.output_dir, asset, outcome)?;
		}
		// After the assets land, generate the projected `<task>.md` for every
		// `<task>.plan.toml` skeleton the pack dropped, so a fresh scaffold ships the
		// rendered plan view beside its structured source. The generated view is NOT a
		// manifest asset (it is derived, and `render`/`render --check` own it), so it is
		// (re)generated here rather than copied. A skeleton that fails to render is a
		// broken pack, reported loudly and fatally (Principle 12) so the scaffold cannot
		// silently ship an unrenderable plan; the assets have already landed, so this
		// only rejects the incoherent template rather than losing work.
		for asset in &assets {
			let Some(stem) = asset.dest.strip_suffix(".plan.toml") else {
				continue;
			};
			let source_path = args.output_dir.join(&asset.dest);
			let rendered = match plan::render_plan(&source_path) {
				Ok(rendered) => rendered,
				Err(problems) => {
					for problem in &problems {
						eprintln!("error: could not render {}: {problem}", asset.dest);
					}
					std::process::exit(2);
				}
			};
			let out_dest = format!("{stem}.md");
			plan::write_rendered(&args.output_dir.join(&out_dest), &rendered)?;
			println!("{:>16}  {out_dest}", "render");
		}
		let changed = outcomes.iter().filter(|o| !matches!(o, Outcome::SkippedExisting)).count();
		let untouched = outcomes.len() - changed;
		println!(
			"Wrote to {} ({changed} changed, {untouched} left untouched).",
			args.output_dir.display()
		);
		// Install the pre-commit hook last, after the assets (including the delegated-to
		// `.agents/hooks/pre-commit`) have landed. Create-if-absent: an existing hook is
		// never clobbered. Any install problem (non-repo, bare repo, filesystem error)
		// is reported and skipped, never failing the scaffold that already succeeded.
		if args.with_precommit_hook {
			match install_precommit_hook(&args.output_dir) {
				HookInstall::Installed(path) =>
					println!("Installed the pre-commit hook at {}.", path.display()),
				HookInstall::Exists(path) => {
					eprintln!(
						"A pre-commit hook already exists at {}; leaving it untouched.",
						path.display()
					);
					print_manual_hook_instructions();
				}
				HookInstall::Skipped(reason) => {
					eprintln!(
						"--with-precommit-hook: skipping the hook install ({reason}); the assets \
						 landed but the hook was not installed."
					);
					print_manual_hook_instructions();
				}
			}
		}
	} else {
		println!("Dry run; nothing written. Pass --write to apply.");
	}
	Ok(())
}

#[cfg(test)]
mod tests {
	use super::*;

	/// A unique scratch directory under the system temp dir for one test.
	fn scratch(name: &str) -> PathBuf {
		let dir = std::env::temp_dir().join(format!(
			"agent-scaffold-poc-{}-{}",
			std::process::id(),
			name
		));
		let _ = fs::remove_dir_all(&dir);
		dir
	}

	#[test]
	fn init_plan_defaults_to_git_and_skips_inside_a_repo() {
		let root = scratch("init-plan");
		fs::create_dir_all(&root).unwrap();
		// Git (the default) in a fresh, non-repo directory would initialise.
		assert_eq!(init_plan(Vcs::Git, &root).unwrap(), InitPlan::Init);
		// `--vcs none` never initialises.
		assert_eq!(init_plan(Vcs::None, &root).unwrap(), InitPlan::None);
		// A directory that is already a repository is skipped (never reinitialised).
		fs::create_dir_all(root.join(".git")).unwrap();
		assert_eq!(init_plan(Vcs::Git, &root).unwrap(), InitPlan::SkipExists);
		// A subdirectory of a repository is skipped too, so no repo is nested.
		let sub = root.join("sub");
		fs::create_dir_all(&sub).unwrap();
		assert_eq!(init_plan(Vcs::Git, &sub).unwrap(), InitPlan::SkipExists);
		let _ = fs::remove_dir_all(&root);
	}

	#[test]
	fn planning_does_not_write() {
		// The dry-run preview computes outcomes without touching the filesystem.
		let root = scratch("plan-only");
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();
		let assets = build_assets(
			&manifest::builtin(),
			&selected,
			Detail::Summary,
			&HashMap::new(),
			false,
			&[],
		)
		.unwrap();
		let outcomes: Vec<Outcome> =
			assets.iter().map(|asset| outcome_of(&root, asset, false)).collect();

		assert!(!outcomes.is_empty());
		assert!(outcomes.iter().all(|o| *o == Outcome::Created), "a fresh dir plans all-Created");
		assert!(!root.exists(), "planning must not create the output directory");
	}

	#[test]
	fn builtin_principles_come_from_the_embedded_pack() {
		// The built-in path reads through the same source the scaffold uses and
		// matches the convenience helper the other tests rely on.
		let via_source = pack_principles(&manifest::builtin()).unwrap();
		assert!(!via_source.is_empty());
		assert_eq!(via_source.len(), pack::default_principles().len());
	}

	#[test]
	fn template_principles_come_from_the_pack_not_the_builtin() {
		let root = scratch("tpl-principles");
		fs::create_dir_all(&root).unwrap();
		fs::write(
			root.join("principles.toml"),
			"[[principle]]\nid = \"custom-one\"\nname = \"Custom One\"\nsummary = \"s\"\n\
			 rationale = \"r\"\ntags = [\"x\"]\ndefault_selected = true\ndefault_order = 1\n",
		)
		.unwrap();
		let principles = pack_principles(&manifest::PackSource::Directory(root.clone())).unwrap();
		assert_eq!(principles.len(), 1);
		assert_eq!(principles[0].id, "custom-one");
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn a_pack_without_principles_has_an_empty_set() {
		let root = scratch("tpl-no-principles");
		fs::create_dir_all(&root).unwrap();
		let principles = pack_principles(&manifest::PackSource::Directory(root.clone())).unwrap();
		assert!(principles.is_empty());
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn first_run_creates_everything() {
		let root = scratch("first-run");
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();
		let results = scaffold(
			&manifest::builtin(),
			&root,
			&selected,
			Detail::Summary,
			&HashMap::new(),
			false,
			false,
		)
		.unwrap();
		assert!(results.iter().all(|(_, o)| *o == Outcome::Created));
		assert!(root.join("AGENTS.md").exists());
		assert!(root.join(".agents/principles.toml").exists());
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn generated_agents_has_principles_and_no_placeholder() {
		let root = scratch("generated");
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();
		scaffold(
			&manifest::builtin(),
			&root,
			&selected,
			Detail::Summary,
			&HashMap::new(),
			false,
			false,
		)
		.unwrap();
		let agents = fs::read_to_string(root.join("AGENTS.md")).unwrap();
		assert!(!agents.contains("{{principles}}"));
		assert!(agents.contains("1. "));
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn rerun_refreshes_reference_but_skips_working() {
		let root = scratch("rerun");
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();
		scaffold(
			&manifest::builtin(),
			&root,
			&selected,
			Detail::Summary,
			&HashMap::new(),
			false,
			false,
		)
		.unwrap();

		// A user edits a working file after the first run.
		fs::write(root.join("AGENTS.md"), "user edits\n").unwrap();

		let results = scaffold(
			&manifest::builtin(),
			&root,
			&selected,
			Detail::Summary,
			&HashMap::new(),
			false,
			false,
		)
		.unwrap();
		let outcome_of =
			|p: &str| results.iter().find(|(path, _)| *path == p).map(|(_, o)| o).unwrap();

		// Reference assets are refreshed; the edited working file is left alone.
		assert_eq!(*outcome_of(".agents/principles.toml"), Outcome::Refreshed);
		assert_eq!(*outcome_of("AGENTS.md"), Outcome::SkippedExisting);
		assert_eq!(fs::read_to_string(root.join("AGENTS.md")).unwrap(), "user edits\n");
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn force_overwrites_working_files() {
		let root = scratch("force");
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();
		scaffold(
			&manifest::builtin(),
			&root,
			&selected,
			Detail::Summary,
			&HashMap::new(),
			false,
			false,
		)
		.unwrap();
		fs::write(root.join("AGENTS.md"), "user edits\n").unwrap();

		let results = scaffold(
			&manifest::builtin(),
			&root,
			&selected,
			Detail::Summary,
			&HashMap::new(),
			true,
			false,
		)
		.unwrap();
		let agents = results.iter().find(|(path, _)| *path == "AGENTS.md").map(|(_, o)| o).unwrap();
		assert_eq!(*agents, Outcome::Overwritten);
		let contents = fs::read_to_string(root.join("AGENTS.md")).unwrap();
		assert_ne!(contents, "user edits\n");
		assert!(contents.starts_with("# Agent guidance"));
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn instrument_off_omits_the_block_and_on_includes_it() {
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();

		// Off (the default): the placeholder is substituted to empty, so the
		// instrumentation section is absent and no literal placeholder remains.
		let off = build_assets(
			&manifest::builtin(),
			&selected,
			Detail::Summary,
			&HashMap::new(),
			false,
			&[],
		)
		.unwrap();
		let agents_off = off.iter().find(|a| a.dest == "AGENTS.md").unwrap();
		assert!(!agents_off.contents.contains("Instrumentation (metrics logging)"));
		assert!(!agents_off.contents.contains("{{instrument}}"));

		// On: the fragment is inlined, carrying the section heading and the log path.
		let on = build_assets(
			&manifest::builtin(),
			&selected,
			Detail::Summary,
			&HashMap::new(),
			true,
			&[],
		)
		.unwrap();
		let agents_on = on.iter().find(|a| a.dest == "AGENTS.md").unwrap();
		assert!(agents_on.contents.contains("Instrumentation (metrics logging)"));
		assert!(agents_on.contents.contains("docs/metrics/workflow.jsonl"));
	}

	#[test]
	fn modules_slot_renders_empty_for_the_module_free_builtin() {
		// The built-in pack declares no modules, so the reserved `{{modules}}` slot
		// substitutes to empty: the placeholder is gone, no module guidance leaks in,
		// and the tail stays byte-stable (one trailing newline, no blank-line run).
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();
		let assets = build_assets(
			&manifest::builtin(),
			&selected,
			Detail::Summary,
			&HashMap::new(),
			false,
			&[],
		)
		.unwrap();
		let agents = assets.iter().find(|a| a.dest == "AGENTS.md").unwrap();
		assert!(!agents.contents.contains("{{modules}}"), "the modules slot must be substituted");
		assert!(agents.contents.ends_with('\n'));
		assert!(
			!agents.contents.ends_with("\n\n"),
			"an empty modules slot leaves no blank-line tail"
		);
	}

	#[test]
	fn checks_module_renders_its_guidance_and_drops_its_assets() {
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();

		// The five assets the checks module drops.
		let checks_assets = [
			".agents/checks.toml",
			".agents/checks/ast-grep/sgconfig.yml",
			".agents/checks/ast-grep/rules/no-dbg-macro.yml",
			".agents/prompts/checks-reviewer.md",
			".agents/hooks/pre-commit",
		];

		// No module: the checks guidance is absent from AGENTS.md and none of the
		// checks assets drop, so the module-free scaffold stays byte-identical.
		let off = build_assets(
			&manifest::builtin(),
			&selected,
			Detail::Summary,
			&HashMap::new(),
			false,
			&[],
		)
		.unwrap();
		let agents_off = off.iter().find(|a| a.dest == "AGENTS.md").unwrap();
		assert!(!agents_off.contents.contains("## Deterministic checks"));
		for dest in checks_assets {
			assert!(!off.iter().any(|a| a.dest == dest), "{dest} must stay out when off");
		}

		// --module checks: the guidance partial is inlined into the `{{modules}}`
		// slot and all five checks assets drop.
		let on = build_assets(
			&manifest::builtin(),
			&selected,
			Detail::Summary,
			&HashMap::new(),
			false,
			&["checks".to_string()],
		)
		.unwrap();
		let agents_on = on.iter().find(|a| a.dest == "AGENTS.md").unwrap();
		assert!(agents_on.contents.contains("## Deterministic checks"));
		assert!(agents_on.contents.contains(".agents/checks.toml"));
		for dest in checks_assets {
			assert!(on.iter().any(|a| a.dest == dest), "{dest} must drop with --module checks");
		}
		// The tail stays clean even with the slot filled: exactly one trailing newline.
		assert!(agents_on.contents.ends_with('\n'));
		assert!(!agents_on.contents.ends_with("\n\n"));
	}

	#[test]
	fn rendered_agents_ends_with_a_single_trailing_newline() {
		let principles = pack::default_principles();
		let selected = pack::resolve_selection(&principles, "default").unwrap();

		// With --instrument off, the empty {{instrument}} substitution must not
		// leave trailing blank lines: the raw output the binary emits (before any
		// external formatter) has to end with exactly one newline, so it stays
		// byte-identical to the pre-instrument output a downstream user without a
		// formatter would see.
		let off = build_assets(
			&manifest::builtin(),
			&selected,
			Detail::Summary,
			&HashMap::new(),
			false,
			&[],
		)
		.unwrap();
		let agents_off = off.iter().find(|a| a.dest == "AGENTS.md").unwrap();
		assert!(agents_off.contents.ends_with('\n'), "AGENTS.md must end with a newline");
		assert!(
			!agents_off.contents.ends_with("\n\n"),
			"AGENTS.md must not end with a blank line when --instrument is off"
		);

		// The single-trailing-newline invariant holds for a rendered asset in
		// general, including with instrumentation on.
		let on = build_assets(
			&manifest::builtin(),
			&selected,
			Detail::Summary,
			&HashMap::new(),
			true,
			&[],
		)
		.unwrap();
		let agents_on = on.iter().find(|a| a.dest == "AGENTS.md").unwrap();
		assert!(agents_on.contents.ends_with('\n'));
		assert!(!agents_on.contents.ends_with("\n\n"));
	}

	/// Initialise a git repository in `dir` (creating it) with a deterministic
	/// identity, for the hook-install tests.
	fn init_git_repo(dir: &Path) {
		fs::create_dir_all(dir).unwrap();
		for args in [
			["init", "-q"].as_slice(),
			["config", "user.email", "test@example.com"].as_slice(),
			["config", "user.name", "Test"].as_slice(),
		] {
			let out =
				std::process::Command::new("git").arg("-C").arg(dir).args(args).output().unwrap();
			assert!(out.status.success(), "git {args:?} failed");
		}
	}

	/// Whether `path` has any executable bit set (Unix only; always true elsewhere,
	/// where the bit is not modelled).
	#[cfg(unix)]
	fn is_executable(path: &Path) -> bool {
		use std::os::unix::fs::PermissionsExt;
		fs::metadata(path).unwrap().permissions().mode() & 0o111 != 0
	}
	#[cfg(not(unix))]
	fn is_executable(_path: &Path) -> bool {
		true
	}

	#[test]
	fn with_precommit_hook_requires_the_checks_module() {
		// The coherence rule the CLI enforces (turning a false into an exit-2 usage
		// error): the flag is coherent only alongside `--module checks`, and is always
		// coherent when not requested.
		assert!(!precommit_coherent(true, &[]), "the hook without --module checks is incoherent");
		assert!(
			!precommit_coherent(true, &["other".to_string()]),
			"another module does not make it coherent"
		);
		assert!(
			precommit_coherent(true, &["checks".to_string()]),
			"--module checks makes the hook coherent"
		);
		assert!(precommit_coherent(false, &[]), "not requesting the hook is always coherent");
	}

	#[test]
	fn install_precommit_hook_creates_it_when_absent() {
		// Create-if-absent, the happy path: no prior hook, so the delegating hook is
		// written, made executable, and delegates to the tracked asset.
		let root = scratch("hook-install-absent");
		init_git_repo(&root);
		let result = install_precommit_hook(&root);
		let path = match result {
			HookInstall::Installed(path) => path,
			other => panic!("expected Installed, got {other:?}"),
		};
		assert!(path.exists(), "the hook file was written");
		assert!(is_executable(&path), "the installed hook is executable");
		let body = fs::read_to_string(&path).unwrap();
		assert!(body.starts_with("#!/bin/sh"), "the hook has a shebang");
		assert!(
			body.contains(".agents/hooks/pre-commit"),
			"the hook delegates to the tracked asset"
		);
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn install_precommit_hook_never_clobbers_an_existing_hook() {
		// Principle 3: an existing pre-commit hook is left byte-untouched, and the
		// install reports `Exists` so the caller can print the manual instructions.
		let root = scratch("hook-install-exists");
		init_git_repo(&root);
		let hooks = root.join(".git").join("hooks");
		fs::create_dir_all(&hooks).unwrap();
		let existing = hooks.join("pre-commit");
		fs::write(&existing, "#!/bin/sh\necho pre-existing\n").unwrap();

		let result = install_precommit_hook(&root);
		match result {
			HookInstall::Exists(path) => assert_eq!(path, existing),
			other => panic!("expected Exists, got {other:?}"),
		}
		// The pre-existing hook is byte-identical: never clobbered.
		assert_eq!(fs::read_to_string(&existing).unwrap(), "#!/bin/sh\necho pre-existing\n");
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	#[cfg(unix)]
	fn install_precommit_hook_never_clobbers_a_valid_symlink() {
		// A pre-commit entry that is a VALID symlink (the documented `ln -s` activation)
		// is an existing entry: it is reported `Exists` and left untouched, and nothing
		// is written through it. Presence is tested with lstat, not `exists()`.
		use std::os::unix::fs::symlink;
		let root = scratch("hook-install-valid-symlink");
		init_git_repo(&root);
		let hooks = root.join(".git").join("hooks");
		fs::create_dir_all(&hooks).unwrap();
		// A real target the symlink points at, with sentinel content.
		let target = root.join("real-hook");
		fs::write(&target, "#!/bin/sh\necho symlink-target\n").unwrap();
		let link = hooks.join("pre-commit");
		symlink(&target, &link).unwrap();

		match install_precommit_hook(&root) {
			HookInstall::Exists(path) => assert_eq!(path, link),
			other => panic!("expected Exists for a valid symlink, got {other:?}"),
		}
		// The entry is still the symlink (not replaced by a regular file), and the
		// target is byte-untouched: nothing was written through it.
		assert!(link.symlink_metadata().unwrap().file_type().is_symlink(), "still a symlink");
		assert_eq!(fs::read_to_string(&target).unwrap(), "#!/bin/sh\necho symlink-target\n");
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	#[cfg(unix)]
	fn install_precommit_hook_never_writes_through_a_dangling_symlink() {
		// The headline safety case: a DANGLING pre-commit symlink (its target is
		// missing) reads as absent under `exists()`, so the old code would write the
		// delegate content THROUGH the link to a path OUTSIDE `.git/hooks/`. lstat sees
		// the link itself, so it is reported `Exists`, left untouched, and the missing
		// target is NOT created.
		use std::os::unix::fs::symlink;
		let root = scratch("hook-install-dangling-symlink");
		init_git_repo(&root);
		let hooks = root.join(".git").join("hooks");
		fs::create_dir_all(&hooks).unwrap();
		// The link's target is deliberately outside .git/hooks and does not exist.
		let missing_target = root.join("escaped-target");
		let link = hooks.join("pre-commit");
		symlink(&missing_target, &link).unwrap();
		assert!(!link.exists(), "a dangling symlink reads as absent under exists()");

		match install_precommit_hook(&root) {
			HookInstall::Exists(path) => assert_eq!(path, link),
			other => panic!("expected Exists for a dangling symlink, got {other:?}"),
		}
		// The link is still a dangling symlink (not overwritten), and no file was
		// written through it to the escaped target.
		assert!(link.symlink_metadata().unwrap().file_type().is_symlink(), "still a symlink");
		assert!(!missing_target.exists(), "nothing was written through the dangling symlink");
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn install_precommit_hook_skips_a_non_repo() {
		// A directory that is not a git repository is skipped with a reason, so the
		// caller notes it rather than failing the scaffold.
		let root = scratch("hook-install-non-repo");
		fs::create_dir_all(&root).unwrap();
		match install_precommit_hook(&root) {
			HookInstall::Skipped(reason) => assert!(reason.contains("not a git repository")),
			other => panic!("expected Skipped, got {other:?}"),
		}
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn install_precommit_hook_skips_a_bare_repo() {
		// A bare repository (no working tree) is skipped: the delegating hook resolves
		// `git rev-parse --show-toplevel`, which has no answer there, so installing one
		// would be inert. Reported `Skipped`, not `Installed` (F6).
		let root = scratch("hook-install-bare");
		fs::create_dir_all(&root).unwrap();
		let out = std::process::Command::new("git")
			.args(["init", "-q", "--bare"])
			.arg(&root)
			.output()
			.unwrap();
		assert!(out.status.success(), "git init --bare failed");
		match install_precommit_hook(&root) {
			HookInstall::Skipped(reason) => assert!(reason.contains("bare")),
			other => panic!("expected Skipped for a bare repo, got {other:?}"),
		}
		// No pre-commit hook was written into the bare repo's hooks dir.
		assert!(!root.join("hooks").join("pre-commit").exists(), "no hook written in a bare repo");
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn install_precommit_hook_does_not_escape_into_an_ancestor_repo() {
		// H1 (high, write-escape): scaffolding into a SUBDIRECTORY of an existing repo
		// must NOT install a hook into the ancestor's `.git/hooks/`. `git rev-parse
		// --git-path hooks` walks up to the ancestor's `.git`, so without the repo-root
		// guard this would drop a (broken) hook outside the output dir and block every
		// commit in the ancestor. The install is skipped and the ancestor's hook dir is
		// left untouched.
		let ancestor = scratch("hook-install-ancestor");
		init_git_repo(&ancestor);
		let sub = ancestor.join("nested").join("project");
		fs::create_dir_all(&sub).unwrap();

		match install_precommit_hook(&sub) {
			HookInstall::Skipped(reason) =>
				assert!(reason.contains("outside"), "reason explains the escape guard: {reason}"),
			other => panic!("expected Skipped for a subdir of an ancestor repo, got {other:?}"),
		}
		// The ancestor repo's pre-commit hook was never created.
		assert!(
			!ancestor.join(".git").join("hooks").join("pre-commit").exists(),
			"nothing was written into the ancestor repo's hooks dir"
		);
		fs::remove_dir_all(&ancestor).unwrap();
	}

	#[test]
	fn install_precommit_hook_does_not_escape_from_a_linked_worktree() {
		// H1 residual (high, write-escape): a git LINKED WORKTREE has its own toplevel
		// (== output_dir, so a toplevel-equality guard passes), but git SHARES hooks in
		// the MAIN repo's `.git/hooks`, outside the worktree. Installing there would
		// drop a broken hook into the main repo and block its commits. The general
		// hooks-dir-inside-output guard catches this: the resolved hooks dir is outside
		// the worktree, so the install is skipped and the main repo's hooks are
		// untouched.
		let main = scratch("hook-install-worktree-main");
		init_git_repo(&main);
		// A commit so `git worktree add` has a base.
		fs::write(main.join("seed.txt"), "seed\n").unwrap();
		for args in [["add", "."].as_slice(), ["commit", "-qm", "seed"].as_slice()] {
			let out =
				std::process::Command::new("git").arg("-C").arg(&main).args(args).output().unwrap();
			assert!(out.status.success(), "git {args:?} failed");
		}
		let linked = scratch("hook-install-worktree-linked");
		let out = std::process::Command::new("git")
			.arg("-C")
			.arg(&main)
			.args(["worktree", "add", "-q"])
			.arg(&linked)
			.output()
			.unwrap();
		assert!(
			out.status.success(),
			"git worktree add failed: {}",
			String::from_utf8_lossy(&out.stderr)
		);

		match install_precommit_hook(&linked) {
			HookInstall::Skipped(reason) =>
				assert!(reason.contains("outside"), "reason explains the escape guard: {reason}"),
			other => panic!("expected Skipped for a linked worktree, got {other:?}"),
		}
		// The MAIN repo's shared pre-commit hook was never created.
		assert!(
			!main.join(".git").join("hooks").join("pre-commit").exists(),
			"nothing was written into the main repo's shared hooks dir"
		);
		let _ = std::process::Command::new("git")
			.arg("-C")
			.arg(&main)
			.args(["worktree", "remove", "--force"])
			.arg(&linked)
			.output();
		fs::remove_dir_all(&main).unwrap();
		let _ = fs::remove_dir_all(&linked);
	}

	#[test]
	fn install_precommit_hook_honours_a_custom_hooks_path_inside_the_output_dir() {
		// The general guard must not over-skip a legitimate install: a custom
		// `core.hooksPath` pointing INSIDE the output dir still installs there. This
		// pins that the hooks-dir-inside-output check passes a within-project custom
		// hooks path.
		let root = scratch("hook-install-custom-hookspath");
		init_git_repo(&root);
		let out = std::process::Command::new("git")
			.arg("-C")
			.arg(&root)
			.args(["config", "core.hooksPath", ".myhooks"])
			.output()
			.unwrap();
		assert!(out.status.success(), "git config core.hooksPath failed");
		match install_precommit_hook(&root) {
			HookInstall::Installed(path) => {
				assert!(
					path.starts_with(root.canonicalize().unwrap()),
					"installed inside the output dir: {}",
					path.display()
				);
				assert!(
					path.ends_with(".myhooks/pre-commit"),
					"installed under the custom hooks path"
				);
			}
			other => panic!(
				"expected Installed for a custom hooks path inside the output dir, got {other:?}"
			),
		}
		fs::remove_dir_all(&root).unwrap();
	}

	#[test]
	fn install_precommit_hook_installs_at_the_repo_root() {
		// The complement of the ancestor-escape guard: when the output dir IS its own
		// repo root, the create-if-absent install still works.
		let root = scratch("hook-install-root");
		init_git_repo(&root);
		match install_precommit_hook(&root) {
			HookInstall::Installed(path) => {
				assert!(
					path.starts_with(root.canonicalize().unwrap()),
					"installed inside the repo"
				);
			}
			other => panic!("expected Installed at the repo root, got {other:?}"),
		}
		fs::remove_dir_all(&root).unwrap();
	}
}
