//! One-directional Markdown-plan -> structured-source migration (Inc 5 PREP).
//!
//! `migrate` reads an existing Markdown plan and the JSONL round log and emits the
//! design-B skeleton this repo is moving to: a `<task>.plan.toml` (the typed
//! `[meta]`/`[[step]]`/`[[question]]`/`[[principle]]` skeleton with the waivers
//! re-homed onto their steps as `[[step.waiver]]` and the baseline on
//! `[meta].w4_baseline`, per Q-46) plus the opaque Markdown sidecars render splices
//! back (`<task>.steps/<slug>.md`, `<task>.questions/<id>.md`, and the front/tail
//! prose sidecars). It reuses the SHIPPED Markdown parsers (`parse_roadmap`,
//! `parse_questions`, `detail_slugs`) for the structured regions and the metrics
//! projections (`parse_waivers`, `parse_baseline`, `parse_rounds`, `parse_decisions`)
//! for the log data, so the migration inherits their exact reading of the source
//! rather than re-implementing it (Principle 16).
//!
//! Faithful, not lossy: every prose block is MOVED verbatim into exactly one sidecar
//! (no reflow, no summarisation), so nothing the render engine cannot regenerate is
//! dropped. The structured Roadmap table, the Open-Questions one-line asks, the status
//! vocabulary, and the numbered principles ARE regenerated by render from the TOML +
//! code constants, so the migration deliberately does not carry those as prose; they
//! are the "expected diffs" a fidelity report classifies (see the Inc 5 brief). This
//! module is PREP only: it emits `[meta].primary = "markdown"` so the live checks keep
//! reading the Markdown plan, and the cutover (flipping `primary` to `toml`, pruning
//! the JSONL waiver/baseline lines, replacing the live `.md`) is a later, gated step.

use {
	super::{
		ROADMAP_BLOCKED_PREFIX,
		source::{
			Increment,
			Meta,
			Primary,
			Principle,
			Question,
			QuestionStatus,
			Sidecars,
			Step,
			StepStatus,
			Waiver,
		},
	},
	crate::metrics::{
		RiskClass,
		WaiverUnit,
		parse_baseline,
		parse_decisions,
		parse_rounds,
		parse_waivers,
	},
	std::collections::{
		BTreeMap,
		BTreeSet,
	},
};

/// The generated migration artifacts: the `<task>.plan.toml` bytes and the sidecar
/// files (each a task-relative path under the plan directory, plus its verbatim
/// bytes). The caller writes them; this module never touches the filesystem, so it is
/// pure and unit-testable (the synthetic pilot exercises it directly).
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Migration {
	/// The rendered `<task>.plan.toml` content.
	pub(crate) plan_toml: String,
	/// The sidecar files as `(task-relative path, verbatim content)`, in a stable
	/// order (front/tail prose, then `<task>.steps/*`, then `<task>.questions/*`).
	pub(crate) sidecars: Vec<(String, String)>,
}

/// The task title carried onto `[meta].title`. Render emits `# <title> plan`, so a
/// live H1 of `# <name> plan` round-trips when the title is `<name>`.
fn extract_title(preamble: &str) -> String {
	for line in preamble.lines() {
		if let Some(rest) = line.strip_prefix("# ") {
			let rest = rest.trim();
			return rest.strip_suffix(" plan").unwrap_or(rest).to_string();
		}
	}
	String::new()
}

/// The preamble (everything before the first `## ` heading) with the H1 title line
/// removed, so what remains is the hand-authored Status narrative + the intro
/// paragraph. Render replaces the Status LINE with a derived one, so this narrative is
/// preserved verbatim in a `_status-narrative` sidecar rather than lost.
fn status_narrative(preamble: &str) -> String {
	let kept: Vec<&str> = preamble.lines().filter(|line| !line.starts_with("# ")).collect();
	trim_block(&kept.join("\n"))
}

/// Split a Markdown document into its leading preamble (before the first `## `
/// heading) and its level-2 sections, each returned as `(heading-text, full-block)`
/// where the block includes the `## ` heading line and runs to just before the next
/// `## ` heading. A nested `### `/`#### ` heading does not end a section.
fn split_h2(markdown: &str) -> (String, Vec<(String, String)>) {
	let mut preamble: Vec<&str> = Vec::new();
	let mut sections: Vec<(String, Vec<&str>)> = Vec::new();
	let mut current: Option<(String, Vec<&str>)> = None;
	for line in markdown.lines() {
		if let Some(heading) = line.strip_prefix("## ").filter(|_| !line.starts_with("### ")) {
			if let Some((name, block)) = current.take() {
				sections.push((name, block));
			}
			current = Some((heading.trim().to_string(), vec![line]));
		} else if let Some((_, block)) = current.as_mut() {
			block.push(line);
		} else {
			preamble.push(line);
		}
	}
	if let Some((name, block)) = current.take() {
		sections.push((name, block));
	}
	let sections =
		sections.into_iter().map(|(name, block)| (name, block.join("\n"))).collect::<Vec<_>>();
	(preamble.join("\n"), sections)
}

/// Trim leading and trailing blank lines from a block, so a spliced sidecar carries no
/// stray blank line render would then reproduce (render trims trailing whitespace per
/// blob but not leading, so both ends are normalised here). Interior blank lines stay.
fn trim_block(text: &str) -> String {
	text.trim_matches('\n').to_string()
}

/// The first backticked value in `text`, or `None` when there is no complete pair.
/// Used to read a fold target from a `decided -> folded into <slug>` status.
fn first_backtick(text: &str) -> Option<String> {
	let start = text.find('`')?;
	let rest = &text[start + 1 ..];
	let end = rest.find('`')?;
	Some(rest[.. end].to_string())
}

/// Whether a Step-Details line is a slugged detail heading (`###`-or-deeper whose text
/// begins with a backticked slug), returning the slug. Mirrors `detail_slugs`.
fn slug_heading(line: &str) -> Option<String> {
	let trimmed = line.trim_start();
	if !trimmed.starts_with("###") {
		return None;
	}
	let after = trimmed.trim_start_matches('#').trim_start();
	if after.starts_with('`') { first_backtick(after) } else { None }
}

/// Whether a Step-Details line is an umbrella heading (`###`-or-deeper whose text is
/// NOT a backticked slug), for example `### TUI polish and tag-based selection`. Its
/// shared-context prose attaches to the next slugged step so nothing is lost.
fn is_umbrella_heading(line: &str) -> bool {
	let trimmed = line.trim_start();
	trimmed.starts_with("###") && slug_heading(line).is_none()
}

/// Map a Markdown Roadmap status cell to the typed `StepStatus` plus any `blocked_by`
/// slugs. The parametric `blocked on <slug>` string becomes the typed `blocked_by`
/// field with a `not-started` status (a blocked step has not started); the live plan
/// carries no blocked rows, so this arm is exercised only by the synthetic pilot.
fn map_step_status(status: &str) -> Result<(StepStatus, Vec<String>), String> {
	let mapped = match status {
		"not started" => StepStatus::NotStarted,
		"in progress" => StepStatus::InProgress,
		"complete" => StepStatus::Complete,
		"skipped" => StepStatus::Skipped,
		"next" => StepStatus::Next,
		"optional" => StepStatus::Optional,
		"deferred" => StepStatus::Deferred,
		other =>
			if let Some(slug) = other.strip_prefix(ROADMAP_BLOCKED_PREFIX) {
				let slug = slug.trim().trim_matches('`').to_string();
				if slug.is_empty() {
					return Err(format!("blocked status with no slug: `{other}`"));
				}
				return Ok((StepStatus::NotStarted, vec![slug]));
			} else {
				return Err(format!("unknown Roadmap status `{other}`"));
			},
	};
	Ok((mapped, Vec::new()))
}

/// Split a principle body `<name><sep><text>` at the earliest `". "` or `": "`
/// separator into `(name, text)`, preserving every word. Render re-joins them as
/// `<n>. <name> - <text>`, so the exact separator is a canonicalisation (an expected
/// diff), not a loss: the full principle text survives across `name` + `text`.
fn split_principle(body: &str) -> (String, String) {
	let dot = body.find(". ");
	let colon = body.find(": ");
	let cut = match (dot, colon) {
		(Some(d), Some(c)) => Some(d.min(c)),
		(Some(d), None) => Some(d),
		(None, Some(c)) => Some(c),
		(None, None) => None,
	};
	match cut {
		Some(index) => (body[.. index].trim().to_string(), body[index + 2 ..].trim().to_string()),
		None => (body.trim().to_string(), String::new()),
	}
}

/// Parse the `## Project Principles` block into the numbered `[[principle]]` records
/// plus the framing prose (the intro before the list and the trailing note), which is
/// returned separately so it can be preserved verbatim in a front sidecar (render
/// regenerates only the numbered list, not the framing).
fn parse_principles(block: &str) -> (Vec<Principle>, String) {
	let mut principles = Vec::new();
	let mut before: Vec<&str> = Vec::new();
	let mut after: Vec<&str> = Vec::new();
	let mut seen_principle = false;
	for line in block.lines() {
		if line.starts_with("## ") {
			continue;
		}
		let is_numbered = line
			.split_once(". ")
			.is_some_and(|(head, _)| !head.is_empty() && head.bytes().all(|b| b.is_ascii_digit()));
		if is_numbered {
			seen_principle = true;
			let (num, body) = line.split_once(". ").expect("numbered line has `. `");
			let n: u64 = num.parse().expect("digits parse");
			let (name, text) = split_principle(body);
			principles.push(Principle {
				n,
				name,
				text,
			});
		} else if seen_principle {
			after.push(line);
		} else {
			before.push(line);
		}
	}
	let intro = trim_block(&before.join("\n"));
	let note = trim_block(&after.join("\n"));
	let framing = match (intro.is_empty(), note.is_empty()) {
		(true, true) => String::new(),
		(false, true) => intro,
		(true, false) => note,
		(false, false) => format!("{intro}\n\n{note}"),
	};
	(principles, framing)
}

/// Split the Open-Questions block into its intro prose (everything between the heading
/// and the first `- `Q-`` item) and the item lines, so the intro is preserved verbatim
/// in a front sidecar (render emits only the one-line-per-item queue, no intro).
fn queue_intro(block: &str) -> String {
	let mut intro: Vec<&str> = Vec::new();
	for line in block.lines() {
		if line.starts_with("## ") {
			continue;
		}
		if line.trim_start().starts_with("- `Q-") {
			break;
		}
		intro.push(line);
	}
	trim_block(&intro.join("\n"))
}

/// Split the `## Roadmap` block into its intro prose (everything before the table),
/// preserved verbatim in a front sidecar since render regenerates the table with no
/// intro slot.
fn roadmap_intro(block: &str) -> String {
	let mut intro: Vec<&str> = Vec::new();
	for line in block.lines() {
		if line.starts_with("## ") {
			continue;
		}
		if line.trim_start().starts_with('|') {
			break;
		}
		intro.push(line);
	}
	trim_block(&intro.join("\n"))
}

/// Split the `## Step Details` block into one verbatim sidecar per step, in document
/// order. The section intro (before the first slugged heading) and each umbrella
/// heading's shared-context prose attach to the NEXT slugged step as a preamble, so
/// concatenating the sidecars in document order reproduces the block body exactly (the
/// data-loss audit asserts this). Returns `(slug, sidecar-body)` pairs.
fn split_step_details(block: &str) -> Result<Vec<(String, String)>, String> {
	let mut segments: Vec<(String, Vec<String>)> = Vec::new();
	let mut pending: Vec<String> = Vec::new();
	let mut current: Option<(String, Vec<String>)> = None;
	for line in block.lines() {
		// Drop only the `## Step Details` heading itself; render regenerates it.
		if line.starts_with("## ") {
			continue;
		}
		if let Some(slug) = slug_heading(line) {
			if let Some(done) = current.take() {
				segments.push(done);
			}
			let mut lines = std::mem::take(&mut pending);
			lines.push(line.to_string());
			current = Some((slug, lines));
		} else if is_umbrella_heading(line) {
			if let Some(done) = current.take() {
				segments.push(done);
			}
			pending.push(line.to_string());
		} else if let Some((_, lines)) = current.as_mut() {
			lines.push(line.to_string());
		} else {
			pending.push(line.to_string());
		}
	}
	if let Some(done) = current.take() {
		segments.push(done);
	}
	if !trim_block(&pending.join("\n")).is_empty() {
		return Err(format!(
			"trailing umbrella/preamble prose with no following step: {:?}",
			trim_block(&pending.join("\n"))
		));
	}
	Ok(segments.into_iter().map(|(slug, lines)| (slug, trim_block(&lines.join("\n")))).collect())
}

/// Build the migration artifacts from a Markdown plan and the JSONL round log.
///
/// `task` names the output family (`<task>.plan.toml`, `<task>.steps/`, etc.).
/// `supersede` supplies the one fact the Markdown `(superseded)` status cannot carry
/// mechanically: the superseding `Q-<n>` for each superseded item (the typed schema
/// requires a resolving `superseded_by`). Returns collected problems on any structural
/// mismatch (a Roadmap slug without a Step-Detail sidecar, an unmapped status, a
/// superseded item with no supplied superseding id) rather than emitting a lossy plan.
pub(crate) fn migrate(
	markdown: &str,
	metrics_jsonl: &str,
	task: &str,
	supersede: &BTreeMap<String, String>,
) -> Result<Migration, Vec<String>> {
	let mut problems: Vec<String> = Vec::new();
	let (preamble, sections) = split_h2(markdown);
	let section = |name: &str| sections.iter().find(|(heading, _)| heading == name).map(|(_, b)| b);

	// -- Structured regions via the shipped parsers --
	let roadmap = super::parse_roadmap(markdown);
	let questions_md = super::parse_questions(markdown);
	let detail = super::detail_slugs(markdown);

	// -- Metrics projections --
	let waivers = parse_waivers(metrics_jsonl);
	let baselines = parse_baseline(metrics_jsonl);
	let rounds = parse_rounds(metrics_jsonl);
	let decisions = parse_decisions(metrics_jsonl);

	// A risk class per task token, so an increment's `risk_class` is inferred from the
	// round records rather than guessed (falls back to low-risk when the log is silent).
	let mut risk_by_task: BTreeMap<&str, RiskClass> = BTreeMap::new();
	for round in &rounds {
		risk_by_task.entry(round.task.as_str()).or_insert(round.risk_class);
	}

	// -- Step Details sidecars (verbatim prose), keyed by slug --
	let step_details = match section("Step Details") {
		Some(block) => match split_step_details(block) {
			Ok(pairs) => pairs,
			Err(problem) => {
				problems.push(problem);
				Vec::new()
			}
		},
		None => {
			problems.push("no `## Step Details` section".to_string());
			Vec::new()
		}
	};
	let detail_body: BTreeMap<String, String> = step_details.iter().cloned().collect();

	// Cross-check the two structured regions agree (every Roadmap slug has a detail and
	// vice versa), the same invariant `validate_plan` enforces on the Markdown source.
	let roadmap_slugs: BTreeSet<&str> = roadmap.iter().map(|s| s.slug.as_str()).collect();
	for step in &roadmap {
		if !detail.contains(&step.slug) {
			problems.push(format!("Roadmap step `{}` has no Step-Detail heading", step.slug));
		}
	}
	for slug in &detail {
		if !roadmap_slugs.contains(slug.as_str()) {
			problems.push(format!("Step-Detail `{slug}` has no Roadmap row"));
		}
	}

	// -- Waivers re-homed onto their steps, and the increments they reference --
	let mut waivers_by_step: BTreeMap<String, Vec<Waiver>> = BTreeMap::new();
	let mut increments_by_step: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
	let mut waiver_counter: BTreeMap<String, usize> = BTreeMap::new();
	for waiver in &waivers {
		let n = waiver_counter.entry(waiver.step.clone()).or_insert(0);
		*n += 1;
		let id = format!("{}-w{n}", waiver.step);
		if waiver.unit == WaiverUnit::Increment {
			if let Some(increment) = &waiver.increment {
				increments_by_step
					.entry(waiver.step.clone())
					.or_default()
					.insert(increment.clone());
			}
		}
		waivers_by_step.entry(waiver.step.clone()).or_default().push(Waiver {
			id,
			unit: waiver.unit,
			increment: waiver.increment.clone(),
			reason: waiver.reason,
			evidence_tier: waiver.evidence_tier,
			evidence: waiver.evidence.clone(),
			note: None,
		});
	}

	// -- Steps --
	let mut steps: Vec<Step> = Vec::new();
	for (index, md_step) in roadmap.iter().enumerate() {
		let (status, blocked_by) = match map_step_status(&md_step.status) {
			Ok(pair) => pair,
			Err(problem) => {
				problems.push(format!("step `{}`: {problem}", md_step.slug));
				(StepStatus::NotStarted, Vec::new())
			}
		};
		let increments: Vec<Increment> = increments_by_step
			.get(&md_step.slug)
			.into_iter()
			.flatten()
			.map(|id| Increment {
				id: id.clone(),
				risk_class: risk_by_task.get(id.as_str()).copied().unwrap_or(RiskClass::LowRisk),
			})
			.collect();
		steps.push(Step {
			slug: md_step.slug.clone(),
			title: detail_title(detail_body.get(&md_step.slug), &md_step.slug),
			status,
			order: (index + 1) as u64,
			blocked_by,
			folds: Vec::new(),
			increments,
			waivers: waivers_by_step.get(&md_step.slug).cloned().unwrap_or_default(),
		});
	}

	// -- Questions (one-line asks; the receipt pointer is auto-set for a decided item
	// that has a JSONL decision record) --
	let receipted: BTreeSet<&str> = decisions.iter().map(|d| d.q_id.as_str()).collect();
	let mut questions: Vec<Question> = Vec::new();
	for md_q in &questions_md {
		let status = &md_q.status;
		let (kind, folded_into, superseded_by) = if status == "open" {
			(QuestionStatus::Open, None, None)
		} else if status == "exploring" {
			(QuestionStatus::Exploring, None, None)
		} else if status == "superseded" {
			match supersede.get(&md_q.id) {
				Some(by) => (QuestionStatus::Superseded, None, Some(by.clone())),
				None => {
					problems.push(format!(
						"question `{}` is `superseded` but no superseding id was supplied (pass \
						 --supersede {}=<Q-n>)",
						md_q.id, md_q.id
					));
					(QuestionStatus::Superseded, None, Some(md_q.id.clone()))
				}
			}
		} else if let Some(rest) = status.strip_prefix(super::QUEUE_FOLD_PREFIX) {
			match first_backtick(rest) {
				Some(slug) => (QuestionStatus::Decided, Some(slug), None),
				None => {
					problems.push(format!("question `{}` fold status has no target slug", md_q.id));
					(QuestionStatus::Decided, None, None)
				}
			}
		} else {
			problems.push(format!("question `{}` has unmapped status `{status}`", md_q.id));
			(QuestionStatus::Open, None, None)
		};
		let receipt =
			if receipted.contains(md_q.id.as_str()) { Some(md_q.id.clone()) } else { None };
		questions.push(Question {
			id: md_q.id.clone(),
			status: kind,
			ask: md_q.ask.clone(),
			folded_into,
			superseded_by,
			receipt,
		});
	}

	// -- Principles + framing prose --
	let (principles, principle_framing) = match section("Project Principles") {
		Some(block) => parse_principles(block),
		None => (Vec::new(), String::new()),
	};

	// -- Orphan tasks: a round-log task whose leading slug owns no Roadmap step --
	let mut orphan_tasks: BTreeSet<String> = BTreeSet::new();
	for task_token in risk_by_task.keys() {
		let leading = strip_increment_suffix(task_token);
		if !roadmap_slugs.contains(leading) {
			orphan_tasks.insert(leading.to_string());
		}
	}

	// -- Baseline --
	let w4_baseline = baselines.last().map(|b| format!("Q-{}", b.questions_through));

	// -- Front/tail prose sidecars, in reading order --
	let mut sidecars: Vec<(String, String)> = Vec::new();
	let mut front_refs: Vec<String> = Vec::new();
	let push_front = |sidecars: &mut Vec<(String, String)>,
	                  front_refs: &mut Vec<String>,
	                  name: &str,
	                  content: String| {
		if content.trim().is_empty() {
			return;
		}
		let file = format!("{task}.{name}.md");
		front_refs.push(file.clone());
		sidecars.push((file, format!("{content}\n")));
	};
	push_front(&mut sidecars, &mut front_refs, "_status-narrative", status_narrative(&preamble));
	if let Some(block) = section("Motivations") {
		push_front(&mut sidecars, &mut front_refs, "motivations", trim_block(block));
	}
	push_front(&mut sidecars, &mut front_refs, "principles-note", principle_framing);
	if let Some(block) = section("Documentation Protocol") {
		push_front(&mut sidecars, &mut front_refs, "documentation-protocol", trim_block(block));
	}
	if let Some(block) = section("Repository Layout and Current Architecture") {
		push_front(&mut sidecars, &mut front_refs, "repo-layout", trim_block(block));
	}
	if let Some(block) = section("Open Questions, Decisions, Issues and Blockers") {
		push_front(&mut sidecars, &mut front_refs, "queue-intro", queue_intro(block));
	}
	if let Some(block) = section("Roadmap") {
		push_front(&mut sidecars, &mut front_refs, "roadmap-intro", roadmap_intro(block));
	}

	// Tail: Success Criteria, spliced verbatim after the generated sections.
	let tail = section("Success Criteria").map(|block| {
		let file = format!("{task}.success-criteria.md");
		sidecars.push((file.clone(), format!("{}\n", trim_block(block))));
		file
	});

	// Step sidecars (one per Roadmap step, in Roadmap order for a stable file list).
	for step in &steps {
		let body = detail_body.get(&step.slug).cloned().unwrap_or_default();
		sidecars.push((format!("{task}.steps/{}.md", step.slug), format!("{body}\n")));
	}
	// Question sidecars: one per question so render (which loads every referenced
	// sidecar) succeeds. The whole ask lives inline in the TOML, so these bodies are
	// empty; a real short-ask/long-body split is an editorial cutover task (see the
	// module note). An empty body renders no `## Question Details` entry.
	for question in &questions {
		sidecars.push((format!("{task}.questions/{}.md", question.id), String::new()));
	}

	let meta = Meta {
		title: extract_title(&preamble),
		w4_baseline,
		primary: Primary::Markdown,
		orphan_tasks: orphan_tasks.into_iter().collect(),
		render_sha256: None,
		sidecars: Sidecars {
			front: front_refs,
			tail,
		},
	};
	let plan = super::PlanToml {
		meta,
		steps,
		questions,
		principles,
	};

	if !problems.is_empty() {
		return Err(problems);
	}

	let plan_toml = match toml::to_string(&plan) {
		Ok(text) => text,
		Err(error) => return Err(vec![format!("serialising the plan.toml failed: {error}")]),
	};
	Ok(Migration {
		plan_toml,
		sidecars,
	})
}

/// The step title carried onto `[[step]].title`, read from the slugged Step-Detail
/// heading (`### `<slug>`: <title>`). Falls back to the slug when the heading has no
/// `: <title>` tail. This is the human-readable one-liner, not prose.
fn detail_title(
	body: Option<&String>,
	slug: &str,
) -> String {
	let Some(body) = body else {
		return slug.to_string();
	};
	for line in body.lines() {
		if slug_heading(line).as_deref() == Some(slug) {
			// After the backticked slug, the title follows a `: ` separator.
			if let Some((_, tail)) = line.split_once(": ") {
				let tail = tail.trim();
				if !tail.is_empty() {
					return tail.to_string();
				}
			}
			break;
		}
	}
	slug.to_string()
}

/// Strip a trailing `-inc<...>` increment suffix from a round-log task token, yielding
/// its leading step slug (`optional-modules-inc2cii` -> `optional-modules`). A token
/// with no such suffix is returned unchanged. Used to detect orphan tasks.
fn strip_increment_suffix(task: &str) -> &str {
	match task.rfind("-inc") {
		Some(index) => &task[.. index],
		None => task,
	}
}

#[cfg(test)]
mod tests {
	use {
		super::*,
		crate::plan::{
			render::render_plan,
			source::{
				parse_toml,
				validate_source,
			},
		},
		std::fs,
	};

	/// A small synthetic Markdown plan exercising every region the migration reads: an
	/// intro/status narrative, motivations, principles + framing, a documentation
	/// protocol, a repo-layout, an Open-Questions queue (open, decided, superseded), a
	/// Roadmap (including a `blocked on` row and an umbrella-grouped sub-step), Step
	/// Details with a section intro + an umbrella preamble, and Success Criteria.
	const SYNTHETIC: &str = concat!(
		"# demo plan\n",
		"\n",
		"Status: hand-authored narrative that render replaces with a derived line.\n",
		"\n",
		"An intro paragraph that must survive verbatim.\n",
		"\n",
		"## Motivations\n",
		"\n",
		"- A motivation that must survive verbatim.\n",
		"\n",
		"## Project Principles\n",
		"\n",
		"These govern the demo.\n",
		"\n",
		"1. First principle: do the first thing well.\n",
		"2. Second principle. Do the second thing too.\n",
		"\n",
		"Note: a trailing principles note that must survive.\n",
		"\n",
		"## Documentation Protocol\n",
		"\n",
		"Protocol prose that must survive verbatim.\n",
		"\n",
		"## Repository Layout and Current Architecture\n",
		"\n",
		"Layout prose that must survive verbatim.\n",
		"\n",
		"## Open Questions, Decisions, Issues and Blockers\n",
		"\n",
		"Queue intro prose that must survive verbatim.\n",
		"\n",
		"- `Q-1` (open) an open ask.\n",
		"- `Q-2` (decided -> folded into `alpha`) a decided ask.\n",
		"- `Q-3` (superseded) a superseded ask.\n",
		"\n",
		"## Roadmap\n",
		"\n",
		"Roadmap intro prose that must survive verbatim.\n",
		"\n",
		"| Step     | Status             |\n",
		"| -------- | ------------------ |\n",
		"| `alpha`  | complete           |\n",
		"| `beta`   | in progress        |\n",
		"| `gamma`  | blocked on `alpha` |\n",
		"\n",
		"## Step Details\n",
		"\n",
		"A Step-Details section intro that must survive verbatim.\n",
		"\n",
		"### `alpha`: The first step\n",
		"\n",
		"The alpha body.\n",
		"\n",
		"### An umbrella heading with shared context\n",
		"\n",
		"Umbrella prose that must attach to the next step verbatim.\n",
		"\n",
		"#### `beta`: The second step\n",
		"\n",
		"The beta body.\n",
		"\n",
		"### `gamma`: The third step\n",
		"\n",
		"The gamma body.\n",
		"\n",
		"## Success Criteria\n",
		"\n",
		"- A success criterion that must survive verbatim.\n",
	);

	/// A JSONL log with a step-unit waiver on `alpha`, an increment-unit record-backed
	/// waiver on `beta`, a baseline, a decision receipt for `Q-2`, and a round record
	/// giving `beta`'s increment its risk class.
	const SYNTHETIC_LOG: &str = concat!(
		r#"{"type":"waiver","task":"x","unit":"step","step":"alpha","reason":"predates-logging","evidence_tier":"self-declared"}"#,
		"\n",
		r#"{"type":"waiver","task":"x","unit":"increment","step":"beta","increment":"beta-inc1","reason":"accepted-at-escalation","evidence_tier":"record-backed","evidence":"beta-inc1"}"#,
		"\n",
		r#"{"type":"round","task":"beta-inc1","artifact":"beta","phase":"work_review","changed_since_prev":true,"outcome":"clean","valid_findings":0,"severities":[],"consecutive_clean":2,"risk_class":"risky"}"#,
		"\n",
		r#"{"type":"baseline","task":"x","questions_through":"Q-1"}"#,
		"\n",
		r#"{"type":"decision","task":"x","q_id":"Q-2","options":["a","b"],"recommendation":"a","chosen":"a"}"#,
		"\n",
	);

	fn run() -> Migration {
		let mut supersede = BTreeMap::new();
		supersede.insert("Q-3".to_string(), "Q-1".to_string());
		migrate(SYNTHETIC, SYNTHETIC_LOG, "demo", &supersede).expect("synthetic migration succeeds")
	}

	#[test]
	fn synthetic_migration_validates_and_renders() {
		let migration = run();
		// The emitted TOML parses and passes the full `validate --source` cross-checks.
		assert!(
			validate_source(&migration.plan_toml).is_empty(),
			"validate_source: {:?}",
			validate_source(&migration.plan_toml)
		);
		let plan = parse_toml(&migration.plan_toml).expect("parses");
		assert_eq!(plan.meta.primary, Primary::Markdown, "PREP stays Markdown-primary");
		assert_eq!(plan.meta.w4_baseline.as_deref(), Some("Q-1"));
		assert_eq!(plan.steps.len(), 3);
		assert_eq!(plan.questions.len(), 3);
		assert_eq!(plan.principles.len(), 2);

		// The blocked row became a typed `blocked_by`, not a status string.
		let gamma = plan.steps.iter().find(|s| s.slug == "gamma").expect("gamma");
		assert_eq!(gamma.blocked_by, vec!["alpha".to_string()]);
		assert_eq!(gamma.status, StepStatus::NotStarted);

		// The waivers re-homed onto their steps with generated ids.
		let alpha = plan.steps.iter().find(|s| s.slug == "alpha").expect("alpha");
		assert_eq!(alpha.waivers.len(), 1);
		assert_eq!(alpha.waivers[0].unit, WaiverUnit::Step);
		let beta = plan.steps.iter().find(|s| s.slug == "beta").expect("beta");
		assert_eq!(beta.waivers.len(), 1);
		assert_eq!(
			beta.increments,
			vec![Increment {
				id: "beta-inc1".to_string(),
				risk_class: RiskClass::Risky,
			}]
		);

		// The decided question carries its receipt (a JSONL decision exists for Q-2).
		let q2 = plan.questions.iter().find(|q| q.id == "Q-2").expect("Q-2");
		assert_eq!(q2.status, QuestionStatus::Decided);
		assert_eq!(q2.folded_into.as_deref(), Some("alpha"));
		assert_eq!(q2.receipt.as_deref(), Some("Q-2"));
		let q3 = plan.questions.iter().find(|q| q.id == "Q-3").expect("Q-3");
		assert_eq!(q3.status, QuestionStatus::Superseded);
		assert_eq!(q3.superseded_by.as_deref(), Some("Q-1"));

		// Render the migration in a scratch dir and confirm the prose survived verbatim.
		let dir =
			std::env::temp_dir().join(format!("agent-scaffold-migrate-{}", std::process::id()));
		let _ = fs::remove_dir_all(&dir);
		fs::create_dir_all(&dir).unwrap();
		fs::write(dir.join("demo.plan.toml"), &migration.plan_toml).unwrap();
		for (path, content) in &migration.sidecars {
			let full = dir.join(path);
			fs::create_dir_all(full.parent().unwrap()).unwrap();
			fs::write(full, content).unwrap();
		}
		let rendered = render_plan(&dir.join("demo.plan.toml")).expect("renders");
		for verbatim in [
			"An intro paragraph that must survive verbatim.",
			"A motivation that must survive verbatim.",
			"Note: a trailing principles note that must survive.",
			"Protocol prose that must survive verbatim.",
			"Layout prose that must survive verbatim.",
			"Queue intro prose that must survive verbatim.",
			"Roadmap intro prose that must survive verbatim.",
			"A Step-Details section intro that must survive verbatim.",
			"Umbrella prose that must attach to the next step verbatim.",
			"The alpha body.",
			"The beta body.",
			"The gamma body.",
			"A success criterion that must survive verbatim.",
		] {
			assert!(rendered.contains(verbatim), "lost verbatim prose: {verbatim:?}\n{rendered}");
		}
		// The umbrella prose renders immediately before its attached step (beta).
		let umbrella_at = rendered.find("Umbrella prose").expect("umbrella");
		let beta_at = rendered.find("The beta body.").expect("beta body");
		assert!(umbrella_at < beta_at, "umbrella prose precedes its attached step");
		// The generated Roadmap shows the typed blocked marker and the inline waiver.
		assert!(rendered.contains("blocked on `alpha`"), "{rendered}");
		assert!(rendered.contains("waived: step predates-logging (self-declared)"), "{rendered}");
		let _ = fs::remove_dir_all(&dir);
	}

	#[test]
	fn step_details_reconstruct_verbatim() {
		// The data-loss property: concatenating the step sidecars in document order,
		// joined by a blank line, reproduces the Step-Details body verbatim.
		let (_, sections) = split_h2(SYNTHETIC);
		let block = &sections.iter().find(|(h, _)| h == "Step Details").unwrap().1;
		let segments = split_step_details(block).expect("splits");
		let reconstructed =
			segments.iter().map(|(_, body)| body.as_str()).collect::<Vec<_>>().join("\n\n");
		// The block body is everything after the heading line, trimmed.
		let body: Vec<&str> = block.lines().skip(1).collect();
		assert_eq!(reconstructed, trim_block(&body.join("\n")));
	}

	#[test]
	fn a_superseded_item_without_a_supplied_id_is_a_problem() {
		let empty = BTreeMap::new();
		let problems = migrate(SYNTHETIC, SYNTHETIC_LOG, "demo", &empty)
			.expect_err("a superseded item with no supplied id must fail");
		assert!(
			problems.iter().any(|p| p.contains("Q-3") && p.contains("superseded")),
			"{problems:?}"
		);
	}
}
